/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        QH_TEXT_CATEGORY:'TEXT',
        QH_TYPE_CONVERT_LABEL:'CONVERSION',
        QH_TYPE_JNDGE_LABEL:'JUDGE',
        QH_VALUE_SLICE_LABEL:'VALUE SLICE',
        QH_STRING_ENCODE_DECODE:'ENCODE DECODE',
        QH_STRING_FIND:'FIND',
        QH_STRING_EDIT:'EDIT',
        QH_STRING_CONVERT_CASE:'CONVERT CASE',
        ascii_to_char:'num->char %1',
        char_to_ascii:'cahr->num %1',
        number_to_text:'Convert to string %1',
        convert_to_int:'Converts the string %1 to integer %2',
        TYPE_DEC:'DEC',
        TYPE_BIN:'BIN',
        TYPE_HEX:'HEX',
        TYPE_OCT:'OCT',
        convert_to_float:'Converts the string %1 to a floating point number',
        convert_round:"Round %1 to keep %2 decimal places",
        convert_to_bool:'Converts the string %1 to Boolean',
        string_start_end:'String %1 is %2 %3',
        startswith:'startswith',
        endswith:'endswith',
        string_isalpha:'String %1 Whether is %2 ?',
        isalpha:'is alpha',
        isdigit:'is digit',
        isalnum:'is alnum',
        isspace:'is space',
        string_get_value:'Gets the %2 th character of string %1',
        string_slice:'Gets the characters of string %1 from %2 to %3',
        text_encode:'Pass the string %1 to %2',
        encode:'encode',
        decode:'decode',
        text_find:'Look for %3 in %1 starting at %2',
        defaultDir:'for default',
        rightDir:'for right',
        text_count:'How many %2s are there in string %1',
        text_replace:'Replaces the text %2 in string %1 with %3',
        text_split:'plit string %1 by text %2',
        text_convert_case:'Convert %1 to %2',
        text_format:'Format the string %1 as %2',
        upper:'upper',
        lower:'lower'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        QH_TEXT_CATEGORY:'文本',
        QH_TYPE_CONVERT_LABEL:'类型转换',
        QH_TYPE_JNDGE_LABEL:'判断',
        QH_VALUE_SLICE_LABEL:'取值与切片',
        QH_STRING_ENCODE_DECODE:'编码和解码',
        QH_STRING_FIND:'查寻',
        QH_STRING_EDIT:'编辑',
        QH_STRING_CONVERT_CASE:'大小写转换',
        ascii_to_char:'数值->字符 %1',
        char_to_ascii:'字符->数值 %1',
        number_to_text:'转换为字符串 %1',
        convert_to_int:'将字符串 %1 转换为整数 %2',
        TYPE_DEC:'十进制',
        TYPE_BIN:'二进制',
        TYPE_HEX:'十六进制',
        TYPE_OCT:'八进制',
        convert_to_float:'将字符串 %1 转换为浮点数',
        convert_round:"四舍五入 %1 保留 %2 位小数",
        convert_to_bool:'将字符串 %1 转换为布尔',
        string_start_end:'字符串 %1 是否 %2 %3',
        startswith:'开始于',
        endswith:'结束于',
        string_isalpha:'字符串 %1 是否都是 %2 ?',
        isalpha:'字母',
        isdigit:'数字',
        isalnum:'数字字母组合',
        isspace:'空格',
        string_get_value:'获取字符串 %1 的 第 %2 个字符',
        string_slice:'获得字符串 %1 从 %2 到 %3 的字符',
        text_encode:'将字符串 %1 进行 %2',
        encode:'编码',
        decode:'解码',
        text_find:'在 %1 中从 %2 开始查找 %3',
        defaultDir:'从左',
        rightDir:'从右',
        text_count:'在字符串 %1 中共有多少个 %2',
        text_replace:'将字符串 %1 中的文本 %2 替换为 %3',
        text_split:'将字符串 %1 按文本 %2 分割',
        text_convert_case:'将 %1 转换为 %2',
        text_format:'将字符串 %1 格式化为 %2',
        upper:'全部大写',
        lower:'全部小写'

    });
    Object.assign(Blockly.ScratchMsgs.locales["zh-tw"], {
        QH_TEXT_CATEGORY:'文本',
        QH_TYPE_CONVERT_LABEL:'類型轉換',
        QH_TYPE_JNDGE_LABEL:'判斷',
        QH_VALUE_SLICE_LABEL:'取值與切片',
        QH_STRING_ENCODE_DECODE:'編碼和解碼',
        QH_STRING_FIND:'查尋',
        QH_STRING_EDIT:'編輯',
        QH_STRING_CONVERT_CASE:'大小寫轉換',
        ascii_to_char:'數值->字元 %1',
        char_to_ascii:'字元->數值 %1',
        number_to_text:'轉換為字串 %1',
        convert_to_int:'將字串 %1 轉換為整數 %2',
        TYPE_DEC:'十進位',
        TYPE_BIN:'二進位',
        TYPE_HEX:'十六進制',
        TYPE_OCT:'八進制',
        convert_to_float:'將字串 %1 轉換為浮點數',
        convert_round:"四捨五入 %1 保留 %2 位小數",
        convert_to_bool:'將字串 %1 轉換為布爾',
        string_start_end:'字串 %1 是否 %2 %3',
        startswith:'開始於',
        endswith:'結束於',
        string_isalpha:'字串 %1 是否都是 %2 ?',
        isalpha:'字母',
        isdigit:'數字',
        isalnum:'數字字母組合',
        isspace:'空格',
        string_get_value:'獲取字串 %1 的 第 %2 個字元',
        string_slice:'獲得字串 %1 從 %2 到 %3 的字元',
        text_encode:'將字串 %1 進行 %2',
        encode:'編碼',
        decode:'解碼',
        text_find:'在 %1 中從 %2 開始查找 %3',
        defaultDir:'從左',
        rightDir:'從右',
        text_count:'在字串 %1 中共有多少個 %2',
        text_replace:'將字串 %1 中的文本 %2 替換為 %3',
        text_split:'將字串 %1 按文本 %2 分割',
        text_convert_case:'將 %1 轉換為 %2',
        text_format:'將字串 %1 格式化為 %2',
        upper:'全部大寫',
        lower:'全部小寫'
    });
    return Blockly;
}

exports = addMsg;
