/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        QH_WEB_CATEGORY:'WEB EDITOR',
        QDP_esp32_web_page_init:'%1 Web Editor Initialization %2 %3',
        QDP_esp32_web_page_add:'Web Editor add %1 ID %2 name %3',
        NumberCard:'Number Card',
        HumidityCard:'Humidity Card',
        StatusCard:'Status Card',
        ButtonCard:'Button Card',
        GaugeChart:'Gauge Chart',
        SliderCard:'Slider Card',
        TemperatureCard:'Temperature Card',
        QDP_esp32_web_page_addTemperatureCard:'Web Editor add temperature ID %1 name %2 type %3',
        QDP_esp32_web_page_addSliderCard:'Web Editor add slider ID %1 name %2 type %3',
        QDP_ESP8266_web_page_Slider_type0:'vertical bottom to top',
        QDP_ESP8266_web_page_Slider_type1:'vertical top to bottom',
        QDP_ESP8266_web_page_Slider_type2:'vertical top to bottom',
        QDP_ESP8266_web_page_Slider_type3:'horizontal right to left',
        QDP_esp32_web_page_attachSliderChanged:'Web Editor attach slider change events',
        QDP_esp32_web_page_Slider_id:'slider ID %1',
        QDP_esp32_web_page_SliderChanged:'%1 Web Editor slider event const char\* id, int value %2 %3',
        QDP_esp32_web_page_attachButtonClick:'Web Editor attach button click events',
        QDP_esp32_web_page_ButtonClick:'%1 Web Editor button event const char\* id %2 %3',
        QDP_esp32_web_page_Button_id:'Button ID %1',
        QDP_esp32_web_page_addLineChart:'Web Editor add line chart ID %1 name %2  value of the X axis(int array or string array) %3 Y axis name %4 Y axis value %5',
        QDP_esp32_web_page_updateLineChart:'Web Editor updata line chart ID %1  value of the X axis(int array or string array) %2 Y axis value(int array) %3',
        QDP_esp32_web_page_update:'Web Editor updata %1 ID %2 value %3',
        QDP_web_serial_init:'%1 Web serial initialization',
        QDP_web_print_data_32:'Web serial port print %1 %2',
        QDP_web_receive_data_32:'%1 Web read string %2 %3',
        QH_SERIAL_PRINT:'PRINT',
        QH_SERIAL_PRINTLN:'PRINTLN',
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        QH_WEB_CATEGORY:'网页编辑',
        QDP_esp32_web_page_init:'%1网页编辑 初始化 %2 %3',
        QDP_esp32_web_page_add:'网页编辑 增加 %1 ID %2 名称 %3',
        NumberCard:'数字',
        HumidityCard:'湿度',
        StatusCard:'状态',
        ButtonCard:'按钮',
        GaugeChart:'仪表盘',
        SliderCard:'滑杆',
        TemperatureCard:'温度',
        QDP_esp32_web_page_addTemperatureCard:'网页编辑 增加湿度 ID %1 名称 %2 类型 %3',
        QDP_esp32_web_page_addSliderCard:'网页编辑 增加滑杆 ID %1 名称 %2 类型 %3',
        QDP_ESP8266_web_page_Slider_type0:'垂直自下而上',
        QDP_ESP8266_web_page_Slider_type1:'垂直自上而下',
        QDP_ESP8266_web_page_Slider_type2:'水平从左到右',
        QDP_ESP8266_web_page_Slider_type3:'水平从左到右',
        QDP_esp32_web_page_attachSliderChanged:'网页编辑 链接滑杆变化事件',
        QDP_esp32_web_page_Slider_id:'滑杆 ID %1',
        QDP_esp32_web_page_SliderChanged:'%1 网页编辑 滑杆事件 const char* id, int value %2 %3',
        QDP_esp32_web_page_attachButtonClick:'网页编辑 链接按钮事件',
        QDP_esp32_web_page_ButtonClick:'%1 网页编辑 按钮事件 const char* id %2 %3',
        QDP_esp32_web_page_Button_id:'按钮 ID %1',
        QDP_esp32_web_page_addLineChart:'网页编辑 增加 折线图 ID %1 名称 %2 X轴的值(int数组或字符串数组 %3 Y轴名字 %4 Y轴值 %5',
        QDP_esp32_web_page_updateLineChart:'网页编辑 更新 折线图 ID %1 X轴的值(int数组或字符串数组) %2 Y轴值(int数组) %3',
        QDP_esp32_web_page_update:'网页编辑 更新 %1 ID %2 值 %3',
        QDP_web_serial_init:'%1 Web 串口 初始化',
        QDP_web_print_data_32:'Web 串口打印 %1 %2',
        QDP_web_receive_data_32:'%1 Web 读取字符串 %2 %3',
        QH_SERIAL_PRINT:'打印',
        QH_SERIAL_PRINTLN:'打印(自动换行)',

    });
    return Blockly;
}

exports = addMsg;
