/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        QH_WEB_PRO_CATEGORY:'Web Editor PRO',
        espdashpro_display_components:'Update card label %1 card unit %2 card type %3 card ID %4 value %5',
        temperature:'temperature',
        humidity:'humidity',
        air_pressure:'air pressure',
        energy:'energy',
        progress_bar:'progress bar',
        tags:'tags',
        espdashpro_state_component:'Set state card label %1 card icon %2 card ID %3 value %4 ',
        success:'success',
        warning:'warning',
        danger:'danger',
        idle:'idle',
        espdashpro_update_chart:'Update chart header %1 card type %2 card ID %3 data origin %4 data origin Y %5',
        BAR_CHART:'BAR CHART',
        LINE_CHART:'LINE CHART',
        AREA_CHART:'AREA CHART',
        PIE_CHART:'PIE CHART',
        espdashpro_display_components1:'Update card label %1 card type %2 card ID %3  value %4',
        BUTTON_CARD:'button',
        SLIDER_CARD:'SLIDER CARD',
        TEXT_INPUT_CARD:'TEXT INPUT CARD',
        espdashpro_get_component_value:'Get card value card label %1 card type %2 card ID %3 return value %4 %5 ',
        espdashpro_get_joystick_value:'Get joystick value labe %1 card type %2 card ID %3 return x,y %4 %5 ',
        bothway:'bothway',
        lockx:'lock x',
        locky:'lock y',
        espdashpro_set_title:'Set webpage title is %1',
        espdashpro_setting_permissions:'Set username %1 password %2',
        espdashpro_add_page:'Add page %1 page ID %2',
        espdashpro_add_statistics:'Add statistics label %1 value %2 ID %3',
        espdashpro_set_component_page:'Set card page type %1 card ID %2 page ID %3',
        status:'status',
        joystick:'joystick'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        QH_WEB_PRO_CATEGORY:'网页编辑PRO',
        espdashpro_display_components:'更新组件 组件标签 %1 组件单位 %2 组件类型 %3 组件 ID %4 值 %5',
        temperature:'温度',
        humidity:'湿度',
        air_pressure:'气压',
        energy:'能源',
        progress_bar:'进度条',
        tags:'自定义标签',
        espdashpro_state_component:'设置状态组件 组件标签 %1 组件图标 %2 组件 ID %3 值 %4 ',
        success:'正常',
        warning:'警告',
        danger:'危险',
        idle:'空闲',
        espdashpro_update_chart:'更新图表 图表表头 %1 组件类型 %2 组件ID %3 数据源 %4 数据源Y %5',
        BAR_CHART:'条形图',
        LINE_CHART:'折线图',
        AREA_CHART:'区域图',
        PIE_CHART:'饼图',
        espdashpro_display_components1:'更新组件 组件标签 %1 组件类型 %2 组件 ID %3  值 %4',
        BUTTON_CARD:'按钮',
        SLIDER_CARD:'滑块',
        TEXT_INPUT_CARD:'文本',
        espdashpro_get_component_value:'获取组件值 组件标签 %1 组件类型 %2 组件 ID %3 返回 value %4 %5 ',
        espdashpro_get_joystick_value:'获取摇杆值 组件标签 %1 组件类型 %2 组件 ID %3  返回 x,y %4 %5',
        bothway:'双向',
        lockx:'横向',
        locky:'纵向',
        espdashpro_set_title:'设置网页标题为 %1',
        espdashpro_setting_permissions:'设置访问用户名 %1 密码 %2',
        espdashpro_add_page:'添加页面 %1 页面 ID %2',
        espdashpro_add_statistics:'添加统计信息 统计标签 %1 值 %2 ID %3',
        espdashpro_set_component_page:'设置组件页面 组件类型 %1 组件ID %2 页面ID %3',
        status:'状态',
        joystick:'摇杆'
    });
    Object.assign(Blockly.ScratchMsgs.locales["zh-tw"], {
        QH_WEB_PRO_CATEGORY:'網頁編輯PRO',
        espdashpro_display_components:'更新組件 組件標籤 %1 組件單位 %2 組件類型 %3 組件 ID %4 值 %5',
        temperature:'溫度',
        humidity:'濕度',
        air_pressure:'氣壓',
        energy:'能源',
        progress_bar:'進度條',
        tags:'自定義標籤',
        espdashpro_state_component:'設置狀態組件 組件標籤 %1 組件圖示 %2 組件 ID %3 值 %4 ',
        success:'正常',
        warning:'警告',
        danger:'危險',
        idle:'空閒',
        espdashpro_update_chart:'更新圖表 圖表表頭 %1 組件類型 %2 組件ID %3 數據源 %4 數據源Y %5',
        BAR_CHART:'條形圖',
        LINE_CHART:'折線圖',
        AREA_CHART:'區域圖',
        PIE_CHART:'餅圖',
        espdashpro_display_components1:'更新組件 組件標籤 %1 組件類型 %2 組件 ID %3  值 %4',
        BUTTON_CARD:'按鈕',
        SLIDER_CARD:'滑塊',
        TEXT_INPUT_CARD:'文本',
        espdashpro_get_component_value:'獲取組件值 組件標籤 %1 組件類型 %2 組件 ID %3 返回 value %4 %5 ',
        espdashpro_get_joystick_value:'獲取搖杆值 組件標籤 %1 組件類型 %2 組件 ID %3  返回 x,y %4 %5',
        bothway:'雙向',
        lockx:'橫向',
        locky:'縱向',
        espdashpro_set_title:'設置網頁標題為 %1',
        espdashpro_setting_permissions:'設置訪問用戶名 %1 密碼 %2',
        espdashpro_add_page:'添加頁面 %1 頁面 ID %2',
        espdashpro_add_statistics:'添加統計資訊 統計標籤 %1 值 %2 ID %3',
        espdashpro_set_component_page:'設置組件頁面 組件類型 %1 組件ID %2 頁面ID %3',
        status:'狀態',
        joystick:'搖杆'

    });
    return Blockly;
}

exports = addMsg;
