/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
    	QH_BUTTON_LABEL:'---BUTTON---',
    	QH_SENSOR_LABEL:'---SENSOR---',
    	QH_MPU6050_LABEL:'---GYRO---',
    	QH_BUZZER_LABEL:'---BUZZER---',
    	QH_IR_LABEL:'---IR---',
    	QH_SENSOR_CATEGORY:'Sensor',
    	QH_ACTUATOR_CATEGORY:'Actuator',
    	QH_SPEECH_CATEGORY:'Speech',
        QH_BUTTON_GENERAL:'Button P3-12',
        QH_BUTTONFUCTION_INIT:'Enable the multi-functionbutton P3-12',
        QH_BUTTONFUCTION_DO:'Multi-function button P3-12 mode %1',
        QH_BUTTONSingleClick:"SingleClick",
		QH_BUTTONDoubleClick:"DoubleClick",
		QH_BUTTONTripleClick:"TripleClick",
		QH_BUTTONSingleLongClick:"SingleLongClick",
		QH_BUTTONDoubleLongClick:"DoubleLongClick",
		QH_BUTTONTripleLongClick:"TripleLongClick",
		QH_LIGHTSENSOR:'Light sensor P7-A1',
		QH_SOUND:'Sound sensor P7-A6',
		QH_POTENTIOMETER:'Potentiometer sensor P8-A7',
		QH_dht11:'Temperature and humidity sensor P6-A2 parameter %1',
		QH_Temperature:'Temperature',
		QH_Humidity:'Humidity',
		QH_MPU6050_update:'MPU6050 (IIC) updata',
		QH_MPU6050_yaw_reset:'YAW reset',
		QH_MPU6050_GETDATA:'Read the value of the gyroscope %1',
		QH_Accel_X:"X Axis Accel", 
        QH_Accel_Y:"Y Axis Accel", 
        QH_Accel_Z:"Z Axis Accel",
        QH_Gyro_X:"X Gyro Accel",
        QH_Gyro_Y:"Y Gyro Accel",
        QH_Gyro_Z:"Z Gyro Accel",
        QH_readTempC:"Temperature",
        QH_MPU6050_readYaw:"Yaw",
        QH_gyro_pitch:"pitch",
        QH_gyro_roll:"roll",
        QH_MPU6050_MOTION_update:'MPU6050 (IIC) motion updata',
        QH_MPU6050_MOTION_GETDATA:'Read the value of the gyroscope %1',
        QH_gyro_isActivity: "Is activity", 
        QH_gyro_isInactivity: "Is inactivity", 
        QH_gyro_isPosActivityOnX: "is Pos activity on X",
        QH_gyro_isNegActivityOnX: "is Neg activity on X",
        QH_gyro_isPosActivityOnY: "is Pos activity on Y",
        QH_gyro_isNegActivityOnY: "is Neg activity on Y",
        QH_gyro_isPosActivityOnZ: "is Pos activity on Z",
        QH_gyro_isNegActivityOnZ:"is Neg activity on Z",
        QH_ledlight:'LED light P1-11 state %1',
        QH_read_ledlight:'Read LED light P1-11',
        QH_ledlight_PWM:'LED P1-11 Value %1',
        QH_rgb_led:'RGB LED P1-10 total %1  NO %2 R %3 G %4 B %5',
        QH_rgb_led2:'RGB LED P1-10 total %1  NO %2 color %3',
        QH_buzzer:'Buzzer P8-A0  frequency %1 duration %2',
        QH_buzzer_music:'Buzzer P8-A0 play music %1 ',
		QH_Voice:'Voice module P8-A7 Play %1 delay %2 ',
		QH_VoicePlayValue:"Voice module P8-A7 Play value %1",
		QH_ir_re2:'Remote control input RC5 P2-9 Keybord %1 Mode %2',
		QH_IrPress:'Press',
		QH_IrPressOn:'Press on',
		QH_ir_send_nec:'Infrared emission %1 Port P2(L3) data %2 bits %3',
		QH_ir_send_raw:'Infrared emission Port P2(L3) %1 Array %2 Array length %3 frequency %4',
		QH_display:'Digit P4 decimal digits %1 number %2',
		QH_displayoff:'Turn off Digit P4'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
    	QH_BUTTON_LABEL:'---按钮---',
    	QH_SENSOR_LABEL:'---传感器---',
    	QH_MPU6050_LABEL:'---陀螺仪---',
    	QH_BUZZER_LABEL:'---蜂鸣器---',
    	QH_IR_LABEL:'---红外---',
    	QH_SENSOR_CATEGORY:'传感器',
    	QH_ACTUATOR_CATEGORY:'执行器',
    	QH_SPEECH_CATEGORY:'语音',
    	QH_COMMUNICATE_CATEGORY:'通讯',
    	QH_SMG_CATEGORY:'数码管',
        QH_BUTTON_GENERAL:'按钮 P3-12',
        QH_BUTTONFUCTION_INIT:'启用多功能按钮 P3-12',
        QH_BUTTONFUCTION_DO:'多功能按钮 P3-12 触发方式 %1',
        QH_BUTTONSingleClick:"单击",
		QH_BUTTONDoubleClick:"双击",
		QH_BUTTONTripleClick:"三击",
		QH_BUTTONSingleLongClick:"长按",
		QH_BUTTONDoubleLongClick:"单击后长按",
		QH_BUTTONTripleLongClick:"双击后长按",
		QH_LIGHTSENSOR:'光线传感器 P7-A1',
		QH_SOUND:'声音传感器 P7-A6',
		QH_POTENTIOMETER:'电位传感器 P8-A7',
		QH_dht11:'温湿度传感器 P6-A2 参数 %1',
		QH_Temperature:'温度',
		QH_Humidity:'湿度',
		QH_MPU6050_update:'启用陀螺仪(IIC)刷新数据',
		QH_MPU6050_yaw_reset:'偏航检测复位',
		QH_MPU6050_GETDATA:'读取陀螺仪的值 %1',
		QH_Accel_X:"X轴加速度", 
        QH_Accel_Y:"Y轴加速度", 
        QH_Accel_Z:"Z轴加速度",
        QH_Gyro_X:"X轴角度",
        QH_Gyro_Y:"Y轴角度",
        QH_Gyro_Z:"Z轴角度",
        QH_readTempC:"温度",
        QH_MPU6050_readYaw:"偏航角",
        QH_gyro_pitch:"俯仰角",
        QH_gyro_roll:"滚转角",
        QH_MPU6050_MOTION_update:'启用陀螺仪(IIC)动作检测刷新数据',
        QH_MPU6050_MOTION_GETDATA:'读取陀螺仪的值 %1',
		QH_gyro_isActivity: "活动", 
		QH_gyro_isInactivity: "静止", 
		QH_gyro_isPosActivityOnX: "X位置活动",
		QH_gyro_isNegActivityOnX: "X角度活动",
		QH_gyro_isPosActivityOnY: "Y位置活动",
		QH_gyro_isNegActivityOnY: "Y角度活动",
		QH_gyro_isPosActivityOnZ: "Z位置活动",
		QH_gyro_isNegActivityOnZ:"Z角度活动",
		QH_ledlight:'LED P1-11 状态 %1',
		QH_read_ledlight:'读取 LED P1-11',
		QH_ledlight_PWM:'LED P1-11 值(0~255) %1',
		QH_rgb_led:'RGB LED P1-10 总数 %1  灯号 %2 R %3 G %4 B %5',
		QH_rgb_led2:'RGB LED P1-10 总数 %1  灯号 %2 颜色 %3',
		QH_buzzer:'蜂鸣器 P8-A0 频率 %1 持续时间 %2',
		QH_buzzer_music:'蜂鸣器 P8-A0 演奏音乐 %1 ',
		QH_Voice:'语音模块 P8-A0 播放 %1 延时 %2 ',
		QH_VoicePlayValue:'语音模块 P8-A0 播放数字值 %1',
		QH_ir_re2:'红外遥控 RC5 P2-9 按键 %1 模式 %2',
		QH_IrPress:'按下',
		QH_IrPressOn:'按住',
		QH_ir_send_nec:'红外发射 模式 %1 端口 P2(L3) 数值 %2 比特数 %3',
		QH_ir_send_raw:'红外发射 端口 P2(L3) %1 数组 %2 数组长度 %3 频率 %4',
		QH_display:'数码管 P4 小数位 %1 数字 %2',
		QH_displayoff:'关闭数码管 P4'
    });
	Object.assign(Blockly.ScratchMsgs.locales["zh-tw"], {
        QH_BUTTON_LABEL:'---按鈕---',
        QH_SENSOR_LABEL:'---感測器---',
        QH_MPU6050_LABEL:'---陀螺儀---',
        QH_BUZZER_LABEL:'---蜂鳴器---',
        QH_IR_LABEL:'---紅外---',
        QH_SENSOR_CATEGORY:'感測器',
        QH_ACTUATOR_CATEGORY:'執行器',
        QH_SPEECH_CATEGORY:'語音',
        QH_COMMUNICATE_CATEGORY:'通訊',
        QH_MP3_CATEGORY:'MP3',
        QH_SMG_CATEGORY:'數碼管',
        QH_BUTTON_GENERAL:'按鈕 P3-12',
        QH_BUTTONFUCTION_INIT:'啟用多功能按鈕 P3-12',
        QH_BUTTONFUCTION_DO:'多功能按鈕 P3-12 觸發方式 %1',
        QH_BUTTONSingleClick:"單擊",
        QH_BUTTONDoubleClick:"雙擊",
        QH_BUTTONTripleClick:"三擊",
        QH_BUTTONSingleLongClick:"長按",
        QH_BUTTONDoubleLongClick:"單擊後長按",
        QH_BUTTONTripleLongClick:"雙擊後長按",
        QH_LIGHTSENSOR:'光線感測器 P7-A1',
        QH_SOUND:'聲音感測器 P7-A6',
        QH_POTENTIOMETER:'電位感測器 P8-A7',
        QH_dht11:'溫濕度感測器 P6-A2 參數 %1',
        QH_Temperature:'溫度',
        QH_Humidity:'濕度',
        QH_MPU6050_update:'啟用陀螺儀(IIC)刷新數據',
        QH_MPU6050_yaw_reset:'偏航檢測複位',
        QH_MPU6050_GETDATA:'讀取陀螺儀的值 %1',
        QH_Accel_X:"X軸加速度", 
        QH_Accel_Y:"Y軸加速度", 
        QH_Accel_Z:"Z軸加速度",
        QH_Gyro_X:"X軸角度",
        QH_Gyro_Y:"Y軸角度",
        QH_Gyro_Z:"Z軸角度",
        QH_readTempC:"溫度",
        QH_MPU6050_readYaw:"偏航角",
        QH_gyro_pitch:"俯仰角",
        QH_gyro_roll:"滾轉角",
        QH_MPU6050_MOTION_update:'啟用陀螺儀(IIC)動作檢測刷新數據',
        QH_MPU6050_MOTION_GETDATA:'讀取陀螺儀的值 %1',
        QH_gyro_isActivity: "活動", 
        QH_gyro_isInactivity: "靜止", 
        QH_gyro_isPosActivityOnX: "X位置活動",
        QH_gyro_isNegActivityOnX: "X角度活動",
        QH_gyro_isPosActivityOnY: "Y位置活動",
        QH_gyro_isNegActivityOnY: "Y角度活動",
        QH_gyro_isPosActivityOnZ: "Z位置活動",
        QH_gyro_isNegActivityOnZ:"Z角度活動",
        QH_ledlight:'LED P-11 狀態 %1',
        QH_read_ledlight:'讀取 LED P1-11',
        QH_ledlight_PWM:'LED P1-11 值(0~255) %1',
        QH_rgb_led:'RGB LED P1-10 總數 %1 燈號 %2 R %3 G %4 B %5',
        QH_rgb_led2:'RGB LED P1-10 總數 %1 燈號 %2 顏色 %3',
        QH_buzzer:'蜂鳴器 P8-A0 頻率 %1 持續時間 %2',
        QH_buzzer_music:'蜂鳴器 P8-A0 演奏音樂 %1 ',
        QH_Voice:'語音模組 P8-A7 播放 %1 延時 %2 ',
        QH_VoicePlayValue:'語音模組 P8-A7 播放數字值 %1',
        QH_ir_re2:'紅外遙控 RC5 P2-9 按鍵 %1 模式 %2',
        QH_IrPress:'按下',
        QH_IrPressOn:'按住',
        QH_ir_send_nec:'紅外發射 模式 %1 端口 P2(L3) 數值 %2 比特數 %3',
        QH_ir_send_raw:'紅外發射 端口 P2(L3) %1 數組 %2 數組長度 %3 頻率 %4',
        QH_display:'數碼管 P4 小數位 %1 數字 %2',
        QH_displayoff:'關閉數碼管 P4'
    });
    return Blockly;
}

exports = addMsg;
