/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        TFT_CATEGORY: 'TFT',
        QDP_qr_code_display:'QR code display content %1 x: %2 y %3 Magnification %4',
        make_arduino_st7735_begin_1:'Initialization TFT %1 RST# %2 CS# %3 DC# %4 MOSI %5 SCLK %6',
        green_label:'green label(ST7735)',
        red_label:'red label(ST7735)',
        black_label:'black label(ST7735)',
        make_arduino_st7735_begin_2:'Initialization TFT %1 RST# %2 CS # %3 DC# %4',
        make_arduino_st7735_backlight_20200703:'Set TFT backlight pin %1 brightness %2',
        make_arduino_st7735_setRotation:'TFT screen rotation %1',
        make_arduino_st7735_set_cursor:'TFT sets the cursor position X %1 Y %2',
        font_micro:'micro',
        font_small:'small',
        font_middle:'middle',
        font_big:'big',
        font_large:'large',
        make_arduino_st7735_setTextSize:'TFT Setting the font size %1',
        setTextColor:'Text Color',
        fillScreen:'fill Screen',
        make_arduino_st7735_set_text_screen_color_2019_10_18:'TFT set %1 to %2',
        arduino_st7735_set_text_background_color_2020_07_01:'TFT set font color font %1 background %2',
        arduino_st7735_set_text_2020_07_02:'TFT draw text position X %1 Y %2 font color %3 backcolor %4 content %5 size %6 newline %7',
        tft_set_EN_Font:'TFT Setting the English Font %1 font size %2 font style %3',
        tft_set_CN_Font:'TFT Setting the Chinese Font %1 font size %2',
        OLED_FONT_chinese1:'Songti small font set 1 (411 words)',
        OLED_FONT_chinese2:'Songti small font set 2 (574 characters)',
        OLED_FONT_chinese3:'Songti small font set 3 (993 characters)',
        OLED_FONT_gb2312a:'Songti large font set A (4041 words)',
        OLED_FONT_gb2312b:'Songti font set B (4531 words)',
        OLED_FONT_gb2312:'Complete Song Dynasty (7539 words)',
        tft_print:'TFT Display Text position X %1 Y %2 color %3 content %4',
        make_arduino_st7735_show_text_2019_10_18:'TFT %1 %2',
        print:'show text(not newline)',
        println:'show text(newline)',
        BIN:'BIN',
        OCT:'OCT',
        DEC:'DEC',
        HEX:'HEX',
        make_arduino_st7735_show_num_2019_10_18:'TFT %1 %2 %3',
        print_num:'show num(not newline)',
        println_num:'show num(newline)',
        make_arduino_st7735_draw_pixel:'TFT draw pixel X %1 Y %2 color %3',
        make_arduino_st7735_draw_line:'TFT draw line start point X %1 Y %2 end point X %3 Y %4 color %5',
        make_arduino_st7735_draw_angle_line_2020_08_10:'TFT  draw line start point X %1 Y %2 Length %3 angle %4 color %5',
        make_arduino_st7735_draw_line1:'TFT %1 start point X %2 Y %3 Length %4 color %5',
        drawFastHLine:'H LINE',
        drawFastVLine:'V LINE',
        make_arduino_st7735_draw_rect_change_2019_10_18:'TFT drwa rect %1 position X %2 Y %3 Width %4 Height %5 color %6',
        draw:'hollow',
        fill:'fill',
        make_arduino_st7735_draw_Roundrect_change_2019_10_18:'TFT drwa rounded rect %1 position X %2 Y %3 Width %4 Height %5 radius %6 color %7',
        make_arduino_st7735_draw_circle:'TFT draw circle %1 position X %2 Y %3 radiu %4 color %5',
        make_arduino_st7735_draw_CircleHelper:'TFT Draw arc center of a circle X %1 Y %2 radius %3 segmental arc %4 color %5',
        make_arduino_oled_draw_CircleHelper_data:'upper left %1 upper right %2 lower left %3 lower right %4',
        make_arduino_st7735_fill_CircleHelper:'TFT Draw fill arc center of circle X %1 Y %2 radius %3 segmental arc %4 Length %5 color %6',
        make_arduino_oled_fill_CircleHelper_data:'upper left&lower left %1 upper right&ower right %2',
        make_arduino_st7735_draw_ellipse:'TFT draw ellipse %1 Center X %2 Y %3 X radius %4 Y radius %5 segmental arc %6 color %7',
        draw_ellipse:'hollow',
        fill_ellipse:'fill',
        make_arduino_st7735_draw_triangle:'TFT drwa triangle %1 X1 %2 Y1 %3 X2 %4 Y2 %5 X3 %6 Y3 %7 color %8'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        TFT_CATEGORY: 'TFT',
        QDP_qr_code_display:'二维码显示 内容 %1 x: %2 y %3 放大倍数 %4',
        make_arduino_st7735_begin_1:'初始化 TFT %1 RST# %2 CS# %3 DC# %4 MOSI %5 SCLK %6',
        green_label:'绿色标签(ST7735)',
        red_label:'红色标签(ST7735)',
        black_label:'黑色标签(ST7735)',
        make_arduino_st7735_begin_2:'初始化TFT %1 RST# %2 CS # %3 DC# %4',
        make_arduino_st7735_backlight_20200703:'设置TFT背光 管脚 %1 亮度 %2',
        make_arduino_st7735_setRotation:'TFT屏幕旋转 %1',
        make_arduino_st7735_set_cursor:'TFT 设置光标位置 X %1 Y %2',
        font_micro:'微小',
        font_small:'小',
        font_middle:'中',
        font_big:'大',
        font_large:'超大',
        make_arduino_st7735_setTextSize:'TFT 设置字体尺寸 %1',
        setTextColor:'字体颜色',
        fillScreen:'屏背景颜色',
        make_arduino_st7735_set_text_screen_color_2019_10_18:'TFT 设置 %1为 %2',
        arduino_st7735_set_text_background_color_2020_07_01:'TFT 设置字体颜色 字体 %1 背景 %2',
        arduino_st7735_set_text_2020_07_02:'TFT 显示文字 位置 X %1 Y %2 字体颜色 %3 背景颜色 %4 内容 %5 尺寸 %6 换行 %7',
        tft_set_EN_Font:'TFT 设置英文字体 %1 字号 %2 字形 %3',
        tft_set_CN_Font:'TFT 设置中文字体 %1 字号 %2',
        OLED_FONT_chinese1:'宋体小字体集1(411字)',
        OLED_FONT_chinese2:'宋体小字体集2(574字)',
        OLED_FONT_chinese3:'宋体小字体集3(993字)',
        OLED_FONT_gb2312a:'宋体大字体集A(4041字)',
        OLED_FONT_gb2312b:'宋体大字体集B(4531字)',
        OLED_FONT_gb2312:'宋体全集(7539字)',
        tft_print:'TFT 显示文本 位置 X %1 Y %2 颜色 %3 内容 %4',
        make_arduino_st7735_show_text_2019_10_18:'TFT %1 %2',
        print:'显示文本(不换行)',
        println:'显示文本(换行)',
        BIN:'二进制',
        OCT:'八进制',
        DEC:'十进制',
        HEX:'十六进制',
        make_arduino_st7735_show_num_2019_10_18:'TFT %1 %2 %3',
        print_num:'显示数字(不换行)',
        println_num:'显示数字(换行)',
        make_arduino_st7735_draw_pixel:'TFT 画点 X %1 Y %2 颜色 %3',
        make_arduino_st7735_draw_line:'TFT 画线 起点 X %1 Y %2 终点 X %3 Y %4 颜色 %5',
        make_arduino_st7735_draw_angle_line_2020_08_10:'TFT 画线 起点 X %1 Y %2 长度 %3 角度 %4 颜色 %5',
        make_arduino_st7735_draw_line1:'TFT %1 起点 X %2 Y %3 长度 %4 颜色 %5',
        drawFastHLine:'水平线',
        drawFastVLine:'垂直线',
        make_arduino_st7735_draw_rect_change_2019_10_18:'TFT 画矩形 %1 左上角 X %2 Y %3 宽度 %4 高度 %5 颜色 %6',
        draw:'空心',
        fill:'实心',
        make_arduino_st7735_draw_Roundrect_change_2019_10_18:'TFT 画圆角矩形 %1 左上角 X %2 Y %3 宽度 %4 高度 %5 半径 %6 颜色 %7',
        make_arduino_st7735_draw_circle:'TFT 画圆 %1 圆心 X %2 Y %3 半径 %4 颜色 %5',
        make_arduino_st7735_draw_CircleHelper:'TFT 画圆弧 圆心 X %1 Y %2 半径 %3 弧段 %4 颜色 %5',
        make_arduino_oled_draw_CircleHelper_data:'左上 %1 右上 %2 左下 %3 右下 %4',
        make_arduino_st7735_fill_CircleHelper:'TFT 画实心圆弧 圆心 X %1 Y %2 半径 %3 弧段 %4 长度 %5 颜色 %6',
        make_arduino_oled_fill_CircleHelper_data:'左上&左下 %1 右上&右下 %2',
        make_arduino_st7735_draw_ellipse:'TFT 画椭圆 %1 圆心 X %2 Y %3 X半径 %4 Y半径 %5 弧段 %6 颜色 %7',
        draw_ellipse:'空心',
        fill_ellipse:'实心',
        make_arduino_st7735_draw_triangle:'TFT 画三角形 %1 X1 %2 Y1 %3 X2 %4 Y2 %5 X3 %6 Y3 %7 颜色 %8'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        TFT_CATEGORY: 'TFT',
        QDP_qr_code_display:'二維碼顯示 內容 %1 x: %2 y %3 放大倍數 %4',
        make_arduino_st7735_begin_1:'初始化 TFT %1 RST# %2 CS# %3 DC# %4 MOSI %5 SCLK %6',
        green_label:'綠色標籤(ST7735)',
        red_label:'紅色標籤(ST7735)',
        black_label:'黑色標籤(ST7735)',
        make_arduino_st7735_begin_2:'初始化TFT %1 RST# %2 CS # %3 DC# %4',
        make_arduino_st7735_backlight_20200703:'設置TFT背光 管腳 %1 亮度 %2',
        make_arduino_st7735_setRotation:'TFT螢幕旋轉 %1',
        make_arduino_st7735_set_cursor:'TFT 設置游標位置 X %1 Y %2',
        font_micro:'微小',
        font_small:'小',
        font_middle:'中',
        font_big:'大',
        font_large:'超大',
        make_arduino_st7735_setTextSize:'TFT 設置字體尺寸 %1',
        setTextColor:'字體顏色',
        fillScreen:'屏背景顏色',
        make_arduino_st7735_set_text_screen_color_2019_10_18:'TFT 設置 %1為 %2',
        arduino_st7735_set_text_background_color_2020_07_01:'TFT 設置字體顏色 字體 %1 背景 %2',
        arduino_st7735_set_text_2020_07_02:'TFT 顯示文字 位置 X %1 Y %2 字體顏色 %3 背景顏色 %4 內容 %5 尺寸 %6 换行 %7',
        tft_set_EN_Font:'TFT 設置英文字體 %1 字型大小 %2 字形 %3',
        tft_set_CN_Font:'TFT 設置中文字體 %1 字型大小 %2',
        OLED_FONT_chinese1:'宋體小字體集1(411字)',
        OLED_FONT_chinese2:'宋體小字體集2(574字)',
        OLED_FONT_chinese3:'宋體小字體集3(993字)',
        OLED_FONT_gb2312a:'宋體大字體集A(4041字)',
        OLED_FONT_gb2312b:'宋體大字體集B(4531字)',
        OLED_FONT_gb2312:'宋體全集(7539字)',
        tft_print:'TFT 顯示文本 位置 X %1 Y %2 顏色 %3 內容 %4',
        make_arduino_st7735_show_text_2019_10_18:'TFT %1 %2',
        print:'顯示文本(不換行)',
        println:'顯示文本(換行)',
        BIN:'二進位',
        OCT:'八進制',
        DEC:'十進位',
        HEX:'十六進制',
        make_arduino_st7735_show_num_2019_10_18:'TFT %1 %2 %3',
        print_num:'顯示數字(不換行)',
        println_num:'顯示數字(換行)',
        make_arduino_st7735_draw_pixel:'TFT 畫點 X %1 Y %2 顏色 %3',
        make_arduino_st7735_draw_line:'TFT 畫線 起點 X %1 Y %2 終點 X %3 Y %4 顏色 %5',
        make_arduino_st7735_draw_angle_line_2020_08_10:'TFT 畫線 起點 X %1 Y %2 長度 %3 角度 %4 顏色 %5',
        make_arduino_st7735_draw_line1:'TFT %1 起點 X %2 Y %3 長度 %4 顏色 %5',
        drawFastHLine:'水平線',
        drawFastVLine:'垂直線',
        make_arduino_st7735_draw_rect_change_2019_10_18:'TFT 畫矩形 %1 左上角 X %2 Y %3 寬度 %4 高度 %5 顏色 %6',
        draw:'空心',
        fill:'實心',
        make_arduino_st7735_draw_Roundrect_change_2019_10_18:'TFT 畫圓角矩形 %1 左上角 X %2 Y %3 寬度 %4 高度 %5 半徑 %6 顏色 %7',
        make_arduino_st7735_draw_circle:'TFT 畫圓 %1 位置 X %2 Y %3 半徑 %4 顏色 %5',
        make_arduino_st7735_draw_CircleHelper:'TFT 畫圓弧 圓心 X %1 Y %2 半徑 %3 弧段 %4 顏色 %5',
        make_arduino_oled_draw_CircleHelper_data:'左上 %1 右上 %2 左下 %3 右下 %4',
        make_arduino_st7735_fill_CircleHelper:'TFT 畫實心圓弧 圓心 X %1 Y %2 半徑 %3 弧段 %4 長度 %5 顏色 %6',
        make_arduino_oled_fill_CircleHelper_data:'左上&左下 %1 右上&右下 %2',
        make_arduino_st7735_draw_ellipse:'TFT 畫橢圓 %1 圓心 X %2 Y %3 X半徑 %4 Y半徑 %5 弧段 %6 顏色 %7',
        draw_ellipse:'空心',
        fill_ellipse:'實心',
        make_arduino_st7735_draw_triangle:'TFT 畫三角形 %1 X1 %2 Y1 %3 X2 %4 Y2 %5 X3 %6 Y3 %7 顏色 %8'
    });
    return Blockly;
}

exports = addMsg;
