/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        HUSKYLENSVISION_CATEGORY: 'HuskyLens VISION',
        huskylens_use_i2c_init:'HuskyLens %1 use I2C %2 initialize ',
        huskylens_request_algorthim:'HuskyLens %1 Switch to algorithm %2 until successful',
        MICROPYTHON_HUSKYLENS_ALGORITHM_OBJECT_TRACKING:'object tracking',
        AipFace:'face recognition',
        MICROPYTHON_HUSKYLENS_ALGORITHM_OBJECT_RECOGNITION:'object identification',
        MICROPYTHON_HUSKYLENS_ALGORITHM_LINE_TRACKING:'line walking',
        catImage_Color:'Color Recognition',
        MICROPYTHON_HUSKYLENS_ALGORITHM_TAG_RECOGNITION:'label Recognition',
        MICROPYTHON_HUSKYLENS_ALGORITHM_OBJECT_CLASSIFICATION:'Object Classify',
        MICROPYTHON_HUSKYLENS_ALGORITHM_QR_CODE_RECOGNTITION:'QR code recognition',
        MICROPYTHON_HUSKYLENS_ALGORITHM_BARCODE_RECOGNTITION:'bar code recognition',
        huskylens_command_request:'HuskyLens %1 Request a data result to store the result',
        huskylens_read_learned_id_count:'HuskyLens %1 Obtain the total number of learned ids from the result',
        huskylens_is_appear_direct:'HuskyLens %1 Gets whether %2 is in the screen from the result',
        RESULT_BLOCK:'BLOCK',
        RESULT_ARROW:'ARROW',
        huskylens_read_block_center_parameter_direct:'HuskyLens %1 Gets the blocks near the center square from the result %2',
        huskylens_read_arrow_center_parameter_direct:'HuskyLens %1 Get the arrows near the center from the result %2',
        BLOCK_PARAMETER_ID:'ID',
        BLOCK_PARAMETER_XCENTER:'X center',
        BLOCK_PARAMETER_YCENTER:'Y center',
        BLOCK_PARAMETER_WIDTH:'width',
        BLOCK_PARAMETER_HEIGHT:'height',
        ARROW_PARAMETER_ID:'ID',
        ARROW_PARAMETER_XORIGIN:'x origin',
        ARROW_PARAMETER_YORIGIN:'y origin',
        ARROW_PARAMETER_XTARGET:'x end point',
        ARROW_PARAMETER_YTARGET:'y end point',
        huskylens_is_learned_id:'HuskyLens %1 Gets whether ID %2 has been learned from the result',
        huskylens_is_appear_id:'HuskyLens %1 Gets ID %2 %3 from the result if it is in the screen',
        huskylens_read_block_id_parameter_direct:'HuskyLens %1 Get %4 of the %3 square of ID %2 from the result',
        huskylens_read_arrow_id_parameter_direct:'HuskyLens %1 Get %4 of the %3 arrow of ID %2 from the result',
        huskylens_read_count:'HuskyLens %1 Get the ID %2 %3 total from the result',
        huskylens_read_blocks_parameter_direct:'HuskyLens %1 Gets %3 of the %2 square from the result',
        huskylens_read_arrows_parameter_direct:'HuskyLens %1 Get %3 of the %2 arrow from the result',
        huskylens_command_request_learn_once:'HuskyLens %1 Automatic learning once ID %2',
        huskylens_command_request_forget:'HuskyLens %1 Forget all the learning data of the current algorithm',
        huskylens_command_request_customnames:'HuskyLens %1 Setting the current algorithm ID %2 name is %3',
        huskylens_command_request_custom_text:'HuskyLens %1 The screen overlays the text %2 x %3 y %4',
        huskylens_command_request_clear_text:'HuskyLens %1 Clear the text displayed on the screen',
        huskylens_command_request_photo_screenshot:'HuskyLens %1 Trigger %2 to save to SD card',
        PHOTO_TAKE_PHOTO:'photo',
        PHOTO_SCREEN_SHOT:'screem shot',
        huskylens_save_load_model_to_SD_card:'HuskyLens %1  %2 The current algorithm data is an SD card %3'

    });

    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        HUSKYLENSVISION_CATEGORY: 'HuskyLens摄像头',
        huskylens_use_i2c_init:'HuskyLens %1 使用I2C %2 初始化 ',
        huskylens_request_algorthim:'HuskyLens %1 切换至算法 %2 直到成功',
        MICROPYTHON_HUSKYLENS_ALGORITHM_OBJECT_TRACKING:'物体追踪',
        AipFace:'人脸识别',
        MICROPYTHON_HUSKYLENS_ALGORITHM_OBJECT_RECOGNITION:'物体识别',
        MICROPYTHON_HUSKYLENS_ALGORITHM_LINE_TRACKING:'巡线',
        catImage_Color:'颜色识别',
        MICROPYTHON_HUSKYLENS_ALGORITHM_TAG_RECOGNITION:'标签识别',
        MICROPYTHON_HUSKYLENS_ALGORITHM_OBJECT_CLASSIFICATION:'物体分类',
        MICROPYTHON_HUSKYLENS_ALGORITHM_QR_CODE_RECOGNTITION:'二维码识别',
        MICROPYTHON_HUSKYLENS_ALGORITHM_BARCODE_RECOGNTITION:'条形码识别',
        huskylens_command_request:'HuskyLens %1 请求一次数据结果 存入结果',
        huskylens_read_learned_id_count:'HuskyLens %1 从结果中获取 已学习ID总数',
        huskylens_is_appear_direct:'HuskyLens %1 从结果中获取 %2 是否在画面中',
        RESULT_BLOCK:'方块',
        RESULT_ARROW:'箭头',
        huskylens_read_block_center_parameter_direct:'HuskyLens %1 从结果中获取 靠近中心方块的 %2',
        huskylens_read_arrow_center_parameter_direct:'HuskyLens %1 从结果中获取 靠近中心箭头的 %2',
        BLOCK_PARAMETER_ID:'ID',
        BLOCK_PARAMETER_XCENTER:'X中心',
        BLOCK_PARAMETER_YCENTER:'Y中心',
        BLOCK_PARAMETER_WIDTH:'宽度',
        BLOCK_PARAMETER_HEIGHT:'高度',
        ARROW_PARAMETER_ID:'',
        ARROW_PARAMETER_XORIGIN:'x起点',
        ARROW_PARAMETER_YORIGIN:'y起点',
        ARROW_PARAMETER_XTARGET:'x终点',
        ARROW_PARAMETER_YTARGET:'y终点',
        huskylens_is_learned_id:'HuskyLens %1 从结果中获取 ID %2 是否已学习',
        huskylens_is_appear_id:'HuskyLens %1 从结果中获取 ID %2 %3 是否在画面中',
        huskylens_read_block_id_parameter_direct:'HuskyLens %1 从结果中获取 ID %2 第 %3 个方块的 %4',
        huskylens_read_arrow_id_parameter_direct:'HuskyLens %1 从结果中获取 ID %2 第 %3 个箭头的 %4',
        huskylens_read_count:'HuskyLens %1 从结果中获取 ID %2 %3 总数',
        huskylens_read_blocks_parameter_direct:'HuskyLens %1 从结果中获取 第 %2 个 方块 的 %3',
        huskylens_read_arrows_parameter_direct:'HuskyLens %1 从结果中获取 第 %2 个 箭头 的 %3',
        huskylens_command_request_learn_once:'HuskyLens %1 自动学习一次 ID %2',
        huskylens_command_request_forget:'HuskyLens %1 遗忘当前算法的所有学习数据',
        huskylens_command_request_customnames:'HuskyLens %1 设置当前算法 ID %2 名字为 %3',
        huskylens_command_request_custom_text:'HuskyLens %1 屏幕叠加显示文字 %2 x %3 y %4',
        huskylens_command_request_clear_text:'HuskyLens %1 清除屏幕显示的文字',
        huskylens_command_request_photo_screenshot:'HuskyLens %1 触发 %2 保存到SD卡',
        PHOTO_TAKE_PHOTO:'拍照',
        PHOTO_SCREEN_SHOT:'截屏',
        huskylens_save_load_model_to_SD_card:'HuskyLens %1  %2 当前算法数据为SD卡 %3'

    });

    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        HUSKYLENSVISION_CATEGORY: 'HuskyLens攝像頭',
        huskylens_use_i2c_init:'HuskyLens %1 使用I2C %2 初始化 ',
        huskylens_request_algorthim:'HuskyLens %1 切換至演算法 %2 直到成功',
        MICROPYTHON_HUSKYLENS_ALGORITHM_OBJECT_TRACKING:'物體追蹤',
        AipFace:'人臉識別',
        MICROPYTHON_HUSKYLENS_ALGORITHM_OBJECT_RECOGNITION:'物體識別',
        MICROPYTHON_HUSKYLENS_ALGORITHM_LINE_TRACKING:'巡線',
        catImage_Color:'顏色識別',
        MICROPYTHON_HUSKYLENS_ALGORITHM_TAG_RECOGNITION:'標籤識別',
        MICROPYTHON_HUSKYLENS_ALGORITHM_OBJECT_CLASSIFICATION:'物體分類',
        MICROPYTHON_HUSKYLENS_ALGORITHM_QR_CODE_RECOGNTITION:'二維碼識別',
        MICROPYTHON_HUSKYLENS_ALGORITHM_BARCODE_RECOGNTITION:'條碼識別',
        huskylens_command_request:'HuskyLens %1 請求一次數據結果 存入結果',
        huskylens_read_learned_id_count:'HuskyLens %1 從結果中獲取 已學習ID總數',
        huskylens_is_appear_direct:'HuskyLens %1 從結果中獲取 %2 是否在畫面中',
        RESULT_BLOCK:'方塊',
        RESULT_ARROW:'箭頭',
        huskylens_read_block_center_parameter_direct:'HuskyLens %1 從結果中獲取 靠近中心方塊的 %2',
        huskylens_read_arrow_center_parameter_direct:'HuskyLens %1 從結果中獲取 靠近中心箭頭的 %2',
        BLOCK_PARAMETER_ID:'ID',
        BLOCK_PARAMETER_XCENTER:'X中心',
        BLOCK_PARAMETER_YCENTER:'Y中心',
        BLOCK_PARAMETER_WIDTH:'寬度',
        BLOCK_PARAMETER_HEIGHT:'高度',
        ARROW_PARAMETER_ID:'',
        ARROW_PARAMETER_XORIGIN:'x起點',
        ARROW_PARAMETER_YORIGIN:'y起點',
        ARROW_PARAMETER_XTARGET:'x終點',
        ARROW_PARAMETER_YTARGET:'y終點',
        huskylens_is_learned_id:'HuskyLens %1 從結果中獲取 ID %2 是否已學習',
        huskylens_is_appear_id:'HuskyLens %1 從結果中獲取 ID %2 %3 是否在畫面中',
        huskylens_read_block_id_parameter_direct:'HuskyLens %1 從結果中獲取 ID %2 第 %3 個方塊的 %4',
        huskylens_read_arrow_id_parameter_direct:'HuskyLens %1 從結果中獲取 ID %2 第 %3 個箭頭的 %4',
        huskylens_read_count:'HuskyLens %1 從結果中獲取 ID %2 %3 總數',
        huskylens_read_blocks_parameter_direct:'HuskyLens %1 從結果中獲取 第 %2 個 方塊 的 %3',
        huskylens_read_arrows_parameter_direct:'HuskyLens %1 從結果中獲取 第 %2 個 箭頭 的 %3',
        huskylens_command_request_learn_once:'HuskyLens %1 自動學習一次 ID %2',
        huskylens_command_request_forget:'HuskyLens %1 遺忘當前演算法的所有學習數據',
        huskylens_command_request_customnames:'HuskyLens %1 設置當前演算法 ID %2 名字為 %3',
        huskylens_command_request_custom_text:'HuskyLens %1 螢幕疊加顯示文字 %2 x %3 y %4',
        huskylens_command_request_clear_text:'HuskyLens %1 清除螢幕顯示的文字',
        huskylens_command_request_photo_screenshot:'HuskyLens %1 觸發 %2 保存到SD卡',
        PHOTO_TAKE_PHOTO:'拍照',
        PHOTO_SCREEN_SHOT:'截屏',
        huskylens_save_load_model_to_SD_card:'HuskyLens %1  %2 當前演算法數據為SD卡 %3'
        
    });

    return Blockly;
}

exports = addMsg;