/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        QH_C02_COLOR_SCREEN_CATEGORY:'Color Screen',
        PY_QDP_blink_32:'Learn QR Code',
        PY_QDP_esp32_display_samll_init:'Color screen initialization %1 Port %2 Baud rate %3',
        PY_QDP_esp32_display_samll_refresh_display:'%1 Color screen refresh display %2',
        PY_QDP_esp32_display_samll_HV:'Color screen direction Port %1 %2',
        QDP_display_samll_HV0:'vertica l90',
        QDP_display_samll_HV1:'transverse 90',
        QDP_display_samll_HV2:'transverse 180',
        QDP_display_samll_HV3:'vertica 270',
        PY_QDP_esp32_display_samll_BL:'Color screen brightness Port %1 brightness 0~255 %2',
        PY_QDP_esp32_display_samll_clr:'Colour screen Port %1 %2 Colour 0~63 %3',
        QDP_display_samll_clr1:'refresh',
        QDP_display_samll_clr2:'background',
        PY_QH_esp32_display_samll_flash_pic:'Picture show Port %1 H/V %2 Mode %3 Picture %4',
        QH_display_samll_HV10:'transverse',
        QH_display_samll_HV11:'vertical',
        QH_display_small_mode0:'normal',
        QH_display_samll_mode1:'transparent',
        PY_QDP_esp32_display_samll_pic:'Image shows Port %1 %2 address %3  starting point X %4 Y %5 width %6 high %7',
        QDP_display_samll_pic0:'normal',
        QDP_display_samll_pic1:'lucency',
        PY_QDP_esp32_customize_display_define_bitmap_data:'Colour screen image name %1 image data %2',
        PY_QDP_esp32_customize_display:'Color screen custom display Port %1 image name %2 starting point X %3 Y %4 width %5 high %6 colour 0~63 %7',
        PY_QDP_esp32_display_samll_PS:'Draw  point Port %1 X %2 Y %3 colour 0~63 %4',
        PY_QDP_esp32_display_samll_PL:'Draw line/box Port %1 %2 starting point X %3 Y %4 end point X %5 Y %6 colour 0~63 %7',
        QDP_display_samll_pl1:'line',
        QDP_display_samll_pl2:'box',
        QDP_display_samll_pl3:'box fill',
        PY_QDP_esp32_display_samll_CIR:'Draw circle Port %1 %2 Center X %3 Y %4 radius %5 colour 0~63 %6',
        MIXLY_QDP_displayhollowround:'hollow',
        MIXLY_QDP_displaysolidround:'solid',
        PY_QDP_esp32_display_samll_DC:'Text Port %1 Font %2 colour 0~63 %3 starting point X %4 Y %5 content %6',
        PY_QDP_esp32_display_samll_SBCDC:'Background colour text Port %1 Font %2 Back colour %3 colour 0~63 %4 starting point X %5 Y %6 content %7',
        PY_QDP_esp32_display_samll_order:'Custom order Port %1 %2',
        PY_QDP_esp32_display_samll_btl:'Color screen Baud rate Port %1 %2'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        QH_C02_COLOR_SCREEN_CATEGORY:'彩屏',
        PY_QDP_blink_32:'学习二维码',
        PY_QDP_esp32_display_samll_init:'彩屏初始化 %1 端口 %2 波特率 %3',
        PY_QDP_esp32_display_samll_refresh_display:'%1 彩屏刷新显示 %2',
        PY_QDP_esp32_display_samll_HV:'彩屏方向 端口 %1 %2',
        QDP_display_samll_HV0:'竖屏90度',
        QDP_display_samll_HV1:'横屏90度',
        QDP_display_samll_HV2:'横屏180度',
        QDP_display_samll_HV3:'竖屏270度',
        PY_QDP_esp32_display_samll_BL:'彩屏亮度 端口 %1 亮度0~255 %2',
        PY_QDP_esp32_display_samll_clr:'颜色 端口 %1 %2 颜色 0~63 %3',
        QDP_display_samll_clr1:'刷屏',
        QDP_display_samll_clr2:'背景',
        PY_QH_esp32_display_samll_flash_pic:'图片显示 端口 %1 横/竖 %2 模式 %3 图片 %4',
        QH_display_samll_HV10:'横屏',
		QH_display_samll_HV11:'竖屏',
        QH_display_small_mode0:'正常',
        QH_display_samll_mode1:'透明',
        PY_QDP_esp32_display_samll_pic:'图片显示 端口 %1 %2 地址 %3 起点 X %4 Y %5 宽 %6 高 %7',
        QDP_display_samll_pic0:'正常',
        QDP_display_samll_pic1:'透明',
        PY_QDP_esp32_customize_display_define_bitmap_data:'彩屏 图像名称 %1 图像数据 %2',
        PY_QDP_esp32_customize_display:'彩屏自定义显示 端口 %1 图像名称 %2 起点 X %3 Y %4 宽 %5 高 %6 颜色 0~63 %7',
        PY_QDP_esp32_display_samll_PS:'画点 端口 %1 X %2 Y %3 颜色 0~63 %4',
        PY_QDP_esp32_display_samll_PL:'画线/框 端口 %1 %2 起点 X %3 Y %4 终点 X %5 Y %6 颜色 0~63 %7',
        QDP_display_samll_pl1:'画线',
        QDP_display_samll_pl2:'空心框',
        QDP_display_samll_pl3:'实心框',
        PY_QDP_esp32_display_samll_CIR:'画圆 端口 %1 %2 圆心 X %3 Y %4 半径 %5 颜色 0~63 %6',
        MIXLY_QDP_displayhollowround:'空心',
        MIXLY_QDP_displaysolidround:'实心',
        PY_QDP_esp32_display_samll_DC:'文本 端口 %1 字号 %2 颜色 0~63 %3 起点 X %4 Y %5 内容 %6',
        PY_QDP_esp32_display_samll_SBCDC:'带底色文本 端口 %1 字号 %2 底色 %3 颜色 0~63 %4 起点 X %5 Y %6 内容 %7',
        PY_QDP_esp32_display_samll_order:'自定义指令 端口 %1 %2',
        PY_QDP_esp32_display_samll_btl:'彩屏波特率 端口 %1 %2'
    });
    Object.assign(Blockly.ScratchMsgs.locales["zh-tw"], {
        QH_C02_COLOR_SCREEN_CATEGORY:'彩屏',
        PY_QDP_blink_32:'學習二維碼',
        PY_QDP_esp32_display_samll_init:'彩屏初始化 %1 端口 %2 串列傳輸速率 %3',
        PY_QDP_esp32_display_samll_refresh_display:'%1 彩屏刷新顯示 %2',
        PY_QDP_esp32_display_samll_HV:'彩屏方向 端口 %1 %2',
        QDP_display_samll_HV0:'豎屏90度',
        QDP_display_samll_HV1:'橫屏90度',
        QDP_display_samll_HV2:'橫屏180度',
        QDP_display_samll_HV3:'豎屏270度',
        PY_QDP_esp32_display_samll_BL:'彩屏亮度 端口 %1 亮度0~255 %2',
        PY_QDP_esp32_display_samll_clr:'顏色 端口 %1 %2 顏色 0~63 %3',
        QDP_display_samll_clr1:'刷屏',
        QDP_display_samll_clr2:'背景',
        PY_QH_esp32_display_samll_flash_pic:'圖片顯示 端口 %1 橫/豎 %2 模式 %3 圖片 %4',
        QH_display_samll_HV10:'橫屏',
        QH_display_samll_HV11:'豎屏',
        QH_display_small_mode0:'正常',
        QH_display_samll_mode1:'透明',
        PY_QDP_esp32_display_samll_pic:'圖片顯示 端口 %1 %2 地址 %3 起點 X %4 Y %5 寬 %6 高 %7',
        QDP_display_samll_pic0:'正常',
        QDP_display_samll_pic1:'透明',
        PY_QDP_esp32_customize_display_define_bitmap_data:'彩屏 圖像名稱 %1 圖像數據 %2',
        PY_QDP_esp32_customize_display:'彩屏自定義顯示 端口 %1 圖像名稱 %2 起點 X %3 Y %4 寬 %5 高 %6 顏色 0~63 %7',
        PY_QDP_esp32_display_samll_PS:'畫點 端口 %1 X %2 Y %3 顏色 0~63 %4',
        PY_QDP_esp32_display_samll_PL:'畫線/框 端口 %1 %2 起點 X %3 Y %4 終點 X %5 Y %6 顏色 0~63 %7',
        QDP_display_samll_pl1:'畫線',
        QDP_display_samll_pl2:'空心框',
        QDP_display_samll_pl3:'實心框',
        PY_QDP_esp32_display_samll_CIR:'畫圓 端口 %1 %2 圓心 X %3 Y %4 半徑 %5 顏色 0~63 %6',
        MIXLY_QDP_displayhollowround:'空心',
        MIXLY_QDP_displaysolidround:'實心',
        PY_QDP_esp32_display_samll_DC:'文本 端口 %1 字型大小 %2 顏色 0~63 %3 起點 X %4 Y %5 內容 %6',
        PY_QDP_esp32_display_samll_SBCDC:'帶底色文本 端口 %1 字型大小 %2 底色 %3 顏色 0~63 %4 起點 X %5 Y %6 內容 %7',
        PY_QDP_esp32_display_samll_order:'自定義指令 端口 %1 %2',
        PY_QDP_esp32_display_samll_btl:'彩屏串列傳輸速率 端口 %1 %2'
    });
    return Blockly;
}

exports = addMsg;
