/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        QH_FILE_CATEGORY:'File',
        storage_fileopen:'Open file path %1 mode %2',
        MICROBIT_PY_STORAGE_READ:'read',
        MICROBIT_PY_STORAGE_WRITE:'write',
        MICROBIT_PY_STORAGE_BIT_READ:'binary read',
        MICROBIT_PY_STORAGE_BIT_WRITE:'binary write',
        storage_file_write:'Writes %1 to file %2',
        storage_get_contents_without_para:'From file %1 %2',
        MICROBIT_PY_STORAGE_ALL:'read content',
        MICROBIT_PY_STORAGE_ONE_LINE:'read line',
        MICROBIT_PY_STORAGE_ALL_LINES:'read all',
        storage_get_contents:'From file %1 %2 not exceeding %3 char',
        storage_can_write_ornot:'File %1 is can write?',
        storage_get_filename:'Get %1 file name',
        storage_close_file:'Close file %1',
        storage_list_all_files:'list all file',
        storage_get_current_dir:'get current directory',
        storage_change_dir:'Change current working directory as %1',
        storage_make_dir:'According to the directory %1 creation %2',
        MICROBIT_PY_STORAGE_MKDIR:'folder',
        MICROBIT_PY_STORAGE_MAKEDIRS:'nested folder',
        storage_delete_file:'%1 %2',
        MICROBIT_PY_STORAGE_DELETE_FILE:'delete file',
        MICROBIT_PY_STORAGE_DELETE_DIRS:'recursion delete folder',
        storage_rename:'Rename the file %1 to %2',
        storage_get_file_size:'Get file %1 size',
        storage_is_file:'Path %1 is %2 ?',
        HTML_FILE:'file',
        MICROBIT_PY_STORAGE_IS_DIR:'Directory',
        storage_file_tell:'return file %1  current read position',
        storage_file_seek:'Set file %1 current position %2 offset %3 char',
        MICROBIT_PY_STORAGE_FILE_SEEK_START:'From the beginning of the file',
        MICROBIT_PY_STORAGE_FILE_SEEK_CURRENT:'From the current of the file',
        MICROBIT_PY_STORAGE_FILE_SEEK_END:'From the ending of the file'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        QH_FILE_CATEGORY:'文件',
        storage_fileopen:'打开文件 路径 %1 模式 %2',
        MICROBIT_PY_STORAGE_READ:'读',
        MICROBIT_PY_STORAGE_WRITE:'写',
        MICROBIT_PY_STORAGE_BIT_READ:'二进制读',
        MICROBIT_PY_STORAGE_BIT_WRITE:'二进制写',
        storage_file_write:'将 %1 写入文件 %2',
        storage_get_contents_without_para:'从文件 %1 %2',
        MICROBIT_PY_STORAGE_ALL:'读取内容',
        MICROBIT_PY_STORAGE_ONE_LINE:'读取一行内容',
        MICROBIT_PY_STORAGE_ALL_LINES:'读取所有内容',
        storage_get_contents:'从文件 %1 %2 不超过 %3 字符',
        storage_can_write_ornot:'文件 %1 是否可写?',
        storage_get_filename:'获取 %1 文件名',
        storage_close_file:'关闭文件 %1',
        storage_list_all_files:'列出所有文件',
        storage_get_current_dir:'获取当前目录',
        storage_change_dir:'改变当前工作目录为 %1',
        storage_make_dir:'根据目录 %1 创建 %2',
        MICROBIT_PY_STORAGE_MKDIR:'文件夹',
        MICROBIT_PY_STORAGE_MAKEDIRS:'嵌套的文件夹',
        storage_delete_file:'%1 %2',
        MICROBIT_PY_STORAGE_DELETE_FILE:'删除文件',
        MICROBIT_PY_STORAGE_DELETE_DIRS:'递归删除目录',
        storage_rename:'将文件 %1 重命名为 %2',
        storage_get_file_size:'获取文件 %1 大小',
        storage_is_file:'路径 %1 是否 %2',
        HTML_FILE:'文件',
        MICROBIT_PY_STORAGE_IS_DIR:'目录',
        storage_file_tell:'返回文件 %1 当前读取的位置',
        storage_file_seek:'设置文件 %1 当前读取位置为%2 偏移 %3 字符',
        MICROBIT_PY_STORAGE_FILE_SEEK_START:'从文件开头位置',
        MICROBIT_PY_STORAGE_FILE_SEEK_CURRENT:'从文件当前位置',
        MICROBIT_PY_STORAGE_FILE_SEEK_END:'从文件结尾位置'
    });
    Object.assign(Blockly.ScratchMsgs.locales["zh-tw"], {
        QH_FILE_CATEGORY:'文件',
        storage_fileopen:'打開檔 路徑 %1 模式 %2',
        MICROBIT_PY_STORAGE_READ:'讀',
        MICROBIT_PY_STORAGE_WRITE:'寫',
        MICROBIT_PY_STORAGE_BIT_READ:'二進位讀',
        MICROBIT_PY_STORAGE_BIT_WRITE:'二進位寫',
        storage_file_write:'將 %1 寫入檔 %2',
        storage_get_contents_without_para:'從檔 %1 %2',
        MICROBIT_PY_STORAGE_ALL:'讀取內容',
        MICROBIT_PY_STORAGE_ONE_LINE:'讀取一行內容',
        MICROBIT_PY_STORAGE_ALL_LINES:'讀取所有內容',
        storage_get_contents:'從檔 %1 %2 不超過 %3 字元',
        storage_can_write_ornot:'檔 %1 是否可寫?',
        storage_get_filename:'獲取 %1 檔案名',
        storage_close_file:'關閉檔 %1',
        storage_list_all_files:'列出所有檔',
        storage_get_current_dir:'獲取當前目錄',
        storage_change_dir:'改變當前工作目錄為 %1',
        storage_make_dir:'根據目錄 %1 創建 %2',
        MICROBIT_PY_STORAGE_MKDIR:'檔夾',
        MICROBIT_PY_STORAGE_MAKEDIRS:'嵌套的檔夾',
        storage_delete_file:'%1 %2',
        MICROBIT_PY_STORAGE_DELETE_FILE:'刪除檔',
        MICROBIT_PY_STORAGE_DELETE_DIRS:'遞歸刪除目錄',
        storage_rename:'將檔 %1 重命名為 %2',
        storage_get_file_size:'獲取檔 %1 大小',
        storage_is_file:'路徑 %1 是否 %2',
        HTML_FILE:'檔',
        MICROBIT_PY_STORAGE_IS_DIR:'目錄',
        storage_file_tell:'返回檔 %1 當前讀取的位置',
        storage_file_seek:'設置檔 %1 當前讀取位置為%2 偏移 %3 字元',
        MICROBIT_PY_STORAGE_FILE_SEEK_START:'從檔開頭位置',
        MICROBIT_PY_STORAGE_FILE_SEEK_CURRENT:'從檔當前位置',
        MICROBIT_PY_STORAGE_FILE_SEEK_END:'從檔結尾位置'
    });
    return Blockly;
}

exports = addMsg;
