/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
    	QH_SENSOR_LABEL:'---SENSOR---',
    	QH_COLOR_LABEL:'---COLOR---',
    	QH_BUZZER_LABEL:'---BUZZER---',
    	QH_SERVO_LABEL:'---SERVO---',
    	QH_DCMOTO_LABEL:'---DCMOTOR---',
    	QH_IR_LABEL:'---IR---',
    	QH_BLUETOOTH_LABEL:'---BLUETOOTH---',
    	QH_SERIAL_LABEL:'---SERIAL---',
    	QH_ZKDISPLAY_LABEL:'---HD DISPLAY---',
    	QH_SMARTCAR01_CATEGORY:'QDProbot Smart car',
		QH_UltraSonicDistanceSensor_Car01:'Utrasonic ranging unit %1',
		QH_LINE_FOLLOWER_Car01:'Line follower Left %1 Right %2',
        QH_rgb_led_Car01:'RGB LED total %1  NO %2 R %3 G %4 B %5',
        QH_rgb_led2_Car01:'RGB LED total %1  NO %2 color %3',
        QH_buzzer_Car01:'Buzzer frequency %1 duration %2',
        QH_buzzer_music_Car01:'Buzzer play music %1 ',
        QH_motor_Car01:'DC motor Port %1 speed(-255~255) %2',
		QH_servomotor180_Car01:'Servo 180° Port %1 Speed %2 Angle(0~180) %3 Interrupt %4',
		QH_Donotinterrupt:'Do not interrupt',
		QH_Interruptible:'Interruptible',
		QH_servomotorread_Car01:'Servo read angle Port %1',
		QH_ir_re2_Car01:'Remote control input RC5 Keybord %1 Mode %2',
		QH_IrPress:'Press',
		QH_IrPressOn:'Press on',
		QH_BT_START:'Bluetooth start P5',
		QH_BT_button:'Bluetooth key P5 %1',
		QH_BT_variable:'Bluetooth variable P5 %1',
		QH_BT_print:'Bluetooth send variable P5 variable 1 %1 variable 2 %2 variable 3 %3 variable 4 %4 variable 5 %5',
		qdp_BT_print_string:'Bluetooth send string P5 variable %1',
        QH_serial_jieshouzhi_Car01:'Serial received if data= %1',
        QH_serial_fasong_Car01:'Serial send Mode %1 Detai1 %2',
        QH_SERIAL_WRITE:'WRITE',
		QH_SERIAL_PRINT:'PRINT',
		QH_SERIAL_PRINTLN:'PRINTLN',
		QH_serial_jieshou_Car01:'Serial received return string',
		QH_serial_suju_Car01:'Serial available',
		qdp_display_START:' %1 Display start P5',
		qdp_display_button:'Display key P5= %1',
		qdp_display_variable:'Display variable P5 %1',
		qdp_display_print:'Send variable to display P5V %1 Value %2',
		qdp_zkpdisplay_sleep:'Screen Sleep Port P5 %1',
		QH_displaysleep1:'Sleep',
		QH_displaysleep0:'Wakeup',qdp_zkpdisplay_buzzer:'Screen buzzer Port P5 frequency %1 Volume(0-100) %2',
		qdp_zkpdisplay_clscolor:'Brush color screen Port P5 Color %1',
		qdp_zkpdisplay_color:'Color %1',
		qdp_zkpdisplay_pic:'Face brush Port P5 %1',
		QH_displaypic1:'love',
		QH_displaypic2:'surprised',
		QH_displaypic3:'sad',
		QH_displaypic4:'Over your face',
		QH_displaypic5:'Smiling face',
		QH_displaypic6:'dizzy',
		QH_displaypic7:'Blink of an eye',
		QH_displaypic8:'praise',
		QH_displaypic9:'Learn the qr code',
		qdp_zkpdisplay_page:'Page jump Port P5 %1',
		QH_displaypage1:'Menu',
		QH_displaypage2:'Remote control/slider',
		QH_displaypage3:'Remote control/variable',
		QH_displaypage4:'Slider',
		QH_displaypage5:'Variable',
		QH_displaypage6:'Keys',
		QH_displaypage7:'Serial',
		QH_displaypage8:'The random number',
		QH_displaypage9:'blank pages',
		qdp_zkpdisplay_drawinground:'Circle Port P5 Type %1 X %2 Y %3 R %4 Decimal color %5',
		QH_displaysolidround:'Solid round',
		QH_displayhollowround:'The hollow circle',
		qdp_zkpdisplay_function1:'Draw Port P5 Type %1 X %2 Y %3 X2W %4 Y2H %5 Decimal color %6',
		QH_displayfunction1fill:'Area filling',
		QH_displayfunction1line:'Line drawing',
		QH_displayfunction1draw:'Draw a rectangular',
		qdp_zkpdisplay_TEXT:'TEXT message Port P5 fill %1 X %2 Y %3 W %4 H %5 Text color %6 Background color %7 Content %8',
		QH_displaybackcolor0:'Cut the figure',
		QH_displaybackcolor1:'monochromatic',
		QH_displaybackcolor2:'picture',
		QH_displaybackcolor3:'No background',
		qdp_zkpdisplay_TEXT_CN:'TEXT message Port P5 fill %1 X %2 Y %3 W %4 H %5 Text color %6 Background color %7 Content %8',
		qdp_zkpdisplay_order:'Custom instruction Port P5 %1'

    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
    	QH_SENSOR_LABEL:'---传感器---',
    	QH_COLOR_LABEL:'---颜色---',
    	QH_BUZZER_LABEL:'---蜂鸣器---',
    	QH_SERVO_LABEL:'---舵机---',
    	QH_DCMOTO_LABEL:'---直流电机---',
    	QH_IR_LABEL:'---红外---',
    	QH_BLUETOOTH_LABEL:'---蓝牙---',
    	QH_SERIAL_LABEL:'---串口---',
    	QH_ZKDISPLAY_LABEL:'---掌控屏---',
    	QH_SMARTCAR01_CATEGORY:'齐护机器人编程小车',
		QH_UltraSonicDistanceSensor_Car01:'超声波测距 单位 %1',
		QH_LINE_FOLLOWER_Car01:'巡线 左路 %1 右路 %2',
		QH_rgb_led_Car01:'RGB LED  总数 %1  灯号 %2 R %3 G %4 B %5',
		QH_rgb_led2_Car01:'RGB LED  总数 %1  灯号 %2 颜色 %3',
		QH_buzzer_Car01:'蜂鸣器 频率 %1 持续时间 %2',
		QH_buzzer_music_Car01:'蜂鸣器 演奏音乐 %1 ',
		QH_motor_Car01:'直流电机 端口 %1 速度(-255~255) %2',
		QH_servomotor180_Car01:'舵机180° 端口 %1 速度 %2 角度(0~180) %3 是否可中断 %4',
		QH_Donotinterrupt:'不中断',
		QH_Interruptible:'中断',
		QH_servomotorread_Car01:'舵机读取角度 端口 %1',
		QH_ir_re2_Car01:'红外遥控 RC5 按键 %1 模式 %2',
		QH_IrPress:'按下',
		QH_IrPressOn:'按住',
		QH_BT_START:'蓝牙数据刷新 P5',
		QH_BT_button:'蓝牙按钮 P5 %1',
		QH_BT_variable:'蓝牙变量 P5 %1',
		QH_BT_print:'蓝牙发送变量 P5 变量1 %1 变量2 %2 变量3 %3 变量4 %4 变量5 %5',
		qdp_BT_print_string:'蓝牙发送字符串 P5 变量 %1',
		QH_serial_jieshouzhi_Car01:'串口接收数据比较 如果数据= %1',
		QH_serial_fasong_Car01:'串口发送 模式 %1 内容 %2',
		QH_SERIAL_WRITE:'原始输出',
		QH_SERIAL_PRINT:'打印',
		QH_SERIAL_PRINTLN:'打印(自动换行)',
		QH_serial_jieshou_Car01:'串口接收 返回字符串',
		QH_serial_suju_Car01:'串口有数据可读',
		qdp_display_START:' %1 启用接收屏数据 P5',
		qdp_display_button:'屏按钮 P5= %1',
		qdp_display_variable:'屏变量 P5 %1',
		qdp_display_print:'发送变量到屏 P5V %1 值 %2',
		qdp_zkpdisplay_sleep:'屏睡眠 端口 P5 %1',
		QH_displaysleep1:'睡眠',
		QH_displaysleep0:'唤醒',
		qdp_zkpdisplay_buzzer:'屏蜂鸣器 端口 P5 频率 %1 音量(0-100) %2',
		qdp_zkpdisplay_clscolor:'颜色刷屏 端口 P5 颜色 %1',
		qdp_zkpdisplay_color:'颜色 %1',
		qdp_zkpdisplay_pic:'表情刷屏 端口 P5 %1',
		QH_displaypic1:'爱心',
		QH_displaypic2:'惊讶',
		QH_displaypic3:'伤心',
		QH_displaypic4:'捂脸',
		QH_displaypic5:'笑脸',
		QH_displaypic6:'晕',
		QH_displaypic7:'眨眼',
		QH_displaypic8:'赞',
		QH_displaypic9:'学习二维码',
		qdp_zkpdisplay_page:'页面跳转 端口 P5 %1',
		QH_displaypage1:'主菜单',
		QH_displaypage2:'遥控/滑块',
		QH_displaypage3:'遥控/变量',
		QH_displaypage4:'滑块',
		QH_displaypage5:'变量V',
		QH_displaypage6:'按键',
		QH_displaypage7:'串口',
		QH_displaypage8:'随机数',
		QH_displaypage9:'空白页',
		qdp_zkpdisplay_drawinground:'画圆 端口 P5 类型 %1 X %2 Y %3 R %4 十进制颜色 %5',
		QH_displaysolidround:'实心圆',
		QH_displayhollowround:'空心圆',
		qdp_zkpdisplay_function1:'画图 端口 P5 类型 %1 X %2 Y %3 X2W %4 Y2H %5 十进制颜色 %6',
		QH_displayfunction1fill:'区域填充',
		QH_displayfunction1line:'画线',
		QH_displayfunction1draw:'画矩形',
		qdp_zkpdisplay_TEXT:'文字信息 端口 P5 填充 %1 X %2 Y %3 W %4 H %5 文字颜色 %6 背景颜色 %7 内容 %8',
		QH_displaybackcolor0:'切图',
		QH_displaybackcolor1:'单色',
		QH_displaybackcolor2:'图片',
		QH_displaybackcolor3:'无背景',
		qdp_zkpdisplay_TEXT_CN:'文字信息 端口 P5 填充 %1 X %2 Y %3 W %4 H %5 文字颜色 %6 背景颜色 %7 内容 %8',
		qdp_zkpdisplay_order:'自定义指令 端口 P5 %1'
    });
	Object.assign(Blockly.ScratchMsgs.locales["zh-tw"], {
        QH_SENSOR_LABEL:'---感測器---',
        QH_COLOR_LABEL:'---顏色---',
        QH_BUZZER_LABEL:'---蜂鳴器---',
        QH_SERVO_LABEL:'---舵機---',
        QH_DCMOTO_LABEL:'---直流電機---',
        QH_IR_LABEL:'---紅外---',
        QH_BLUETOOTH_LABEL:'---藍牙---',
        QH_SERIAL_LABEL:'---串口---',
        QH_ZKDISPLAY_LABEL:'---掌控屏---',
        QH_SMARTCAR01_CATEGORY:'齊護機器人編程小車',
        QH_UltraSonicDistanceSensor_Car01:'超聲波測距 單位 %1',
        QH_LINE_FOLLOWER_Car01:'巡線 左路 %1 右路 %2',
        QH_rgb_led_Car01:'RGB LED 總數 %1 燈號 %2 R %3 G %4 B %5',
        QH_rgb_led2_Car01:'RGB LED 總數 %1 燈號 %2 顏色 %3',
        QH_buzzer_Car01:'蜂鳴器 頻率 %1 持續時間 %2',
        QH_buzzer_music_Car01:'蜂鳴器 演奏音樂 %1 ',
        QH_motor_Car01:'直流電機 端口 %1 速度(-255~255) %2',
        QH_servomotor180_Car01:'舵機180° 端口 %1 速度 %2 角度(0~180) %3 是否可中斷 %4',
        QH_Donotinterrupt:'不中斷',
        QH_Interruptible:'中斷',
        QH_servomotorread_Car01:'舵機讀取角度 端口 %1',
        QH_ir_re2_Car01:'紅外遙控 RC5 按鍵 %1 模式 %2',
        QH_IrPress:'按下',
        QH_IrPressOn:'按住',
        QH_BT_START:'藍牙數據刷新 P5',
        QH_BT_button:'藍牙按鈕 P5 %1',
        QH_BT_variable:'藍牙變數 P5 %1',
        QH_BT_print:'藍牙發送變數 P5 變數1 %1 變數2 %2 變數3 %3 變數4 %4 變數5 %5',
        qdp_BT_print_string:'藍牙發送字串 P5 變數 %1',
        QH_serial_jieshouzhi_Car01:'串口接收數據比較 如果數據= %1',
        QH_serial_fasong_Car01:'串口發送 模式 %1 內容 %2',
        QH_SERIAL_WRITE:'原始輸出',
        QH_SERIAL_PRINT:'列印',
        QH_SERIAL_PRINTLN:'列印(自動換行)',
        QH_serial_jieshou_Car01:'串口接收 返回字串',
        QH_serial_suju_Car01:'串口有數據可讀',
        qdp_display_START:' %1 啟用接收屏數據 P5',
        qdp_display_button:'屏按鈕 P5= %1',
        qdp_display_variable:'屏變數 P5 %1',
        qdp_display_print:'發送變數到屏 P5V %1 值 %2',
        qdp_zkpdisplay_sleep:'屏睡眠 端口 P5 %1',
        QH_displaysleep1:'睡眠',
        QH_displaysleep0:'喚醒',
        qdp_zkpdisplay_buzzer:'屏蜂鳴器 端口 P5 頻率 %1 音量(0-100) %2',
        qdp_zkpdisplay_clscolor:'顏色刷屏 端口 P5 顏色 %1',
        qdp_zkpdisplay_color:'顏色 %1',
        qdp_zkpdisplay_pic:'表情刷屏 端口 P5 %1',
        QH_displaypic1:'愛心',
        QH_displaypic2:'驚訝',
        QH_displaypic3:'傷心',
        QH_displaypic4:'捂臉',
        QH_displaypic5:'笑臉',
        QH_displaypic6:'暈',
        QH_displaypic7:'眨眼',
        QH_displaypic8:'贊',
        QH_displaypic9:'學習二維碼',
        qdp_zkpdisplay_page:'頁面跳轉 端口 P5 %1',
        QH_displaypage1:'主菜單',
        QH_displaypage2:'遙控/滑塊',
        QH_displaypage3:'遙控/變數',
        QH_displaypage4:'滑塊',
        QH_displaypage5:'變數V',
        QH_displaypage6:'按鍵',
        QH_displaypage7:'串口',
        QH_displaypage8:'亂數',
        QH_displaypage9:'空白頁',
        qdp_zkpdisplay_drawinground:'畫圓 端口 P5 類型 %1 X %2 Y %3 R %4 十進位顏色 %5',
        QH_displaysolidround:'實心圓',
        QH_displayhollowround:'空心圓',
        qdp_zkpdisplay_function1:'畫圖 端口 P5 類型 %1 X %2 Y %3 X2W %4 Y2H %5 十進位顏色 %6',
        QH_displayfunction1fill:'區域填充',
        QH_displayfunction1line:'畫線',
        QH_displayfunction1draw:'畫矩形',
        qdp_zkpdisplay_TEXT:'文字資訊 端口 P5 填充 %1 X %2 Y %3 W %4 H %5 文字顏色 %6 背景顏色 %7 內容 %8',
        QH_displaybackcolor0:'切圖',
        QH_displaybackcolor1:'單色',
        QH_displaybackcolor2:'圖片',
        QH_displaybackcolor3:'無背景',
        qdp_zkpdisplay_TEXT_CN:'文字資訊 端口 P5 填充 %1 X %2 Y %3 W %4 H %5 文字顏色 %6 背景顏色 %7 內容 %8',
        qdp_zkpdisplay_order:'自定義指令 端口 P5 %1'
    });
    return Blockly;
}

exports = addMsg;
