/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
    	QH_BUTTON_LABEL:'---BUTTON---',
    	QH_SENSOR_LABEL:'---SENSOR---',
    	QH_BUZZER_LABEL:'---BUZZER---',
    	QH_SERVO_LABEL:'---SERVO---',
    	QH_DCMOTO_LABEL:'---DCMOTOR---',
    	QH_IR_LABEL:'---IR---',
    	QH_SERIAL_LABEL:'---SERIAL---',
    	QH_SENSOR_CATEGORY:'Sensor',
    	QH_ACTUATOR_CATEGORY:'Actuator',
    	QH_COMMUNICATE_CATEGORY:'Communicate',
    	QH_SMG_CATEGORY:'Display',
    	QH_LEFT:'Left',
    	QH_RIGHT:'Right',
        QH_BUTTON_GENERAL:'Button pin %1  L/R %2',
        QH_BUTTON_BOTH:'L OR R button PIN %1',
        QH_BUTTONFUCTION_INIT:'Enable the multi-functionbutton port %1',
        QH_BUTTONFUCTION_DO:'Multi-function button Port %1 L/R %2 Trigger mode %3',
        QH_BUTTONSingleClick:"SingleClick",
		QH_BUTTONDoubleClick:"DoubleClick",
		QH_BUTTONTripleClick:"TripleClick",
		QH_BUTTONSingleLongClick:"SingleLongClick",
		QH_BUTTONDoubleLongClick:"DoubleLongClick",
		QH_BUTTONTripleLongClick:"TripleLongClick",
		QH_UltraSonicDistanceSensor:'Utrasonic ranging Port %1 unit %2',
		QH_LINE_FOLLOWER:'Line follower Port %1 Left %2 Right %3',
		QH_LIGHTSENSOR:'Light sensor Port %1',
		QH_SOUND:'Sound sensor Port %1',
		QH_POTENTIOMETER:'Potentiometer sensor Port %1 L/R %2',
		QH_dht11:'Temperature and humidity sensor Port %1 parameter %2',
		QH_Temperature:'Temperature',
		QH_Humidity:'Humidity',
        QH_ledlight:'LED light Port %1 L/R %2 state %3',
        QH_read_ledlight:'Read LED light Port %1 L/R %2 ',
        QH_ledlight_PWM:'LED Port %1 L/R %2 Value %3',
        QH_rgb_led:'RGB LED Port %1 total %2  NO %3 R %4 G %5 B %6',
        QH_rgb_led2:'RGB LED Port %1 total %2  NO %3 color %4',
        QH_buzzer:'Buzzer Port %1  frequency %2 duration %3',
        QH_buzzer_music:'Buzzer Port %1 play music %2 ',
        QH_motor:'DC motor Port %1 speed(-255~255) %2',
        QH_servomotor360:'Servo 360° Port %1 Direction %2 Speed(0~10) %3',
        QH_CW:'CW',
		QH_CCW:'CCW',
		QH_servomotor180:'Servo 180° Port %1 Speed %2 Angle(0~180) %3 Interrupt %4',
		QH_Donotinterrupt:'Do not interrupt',
		QH_Interruptible:'Interruptible',
		QH_servomotorread:'Servo read angle Port %1',
		QH_ir_re2:'Remote control input RC5 Port %1 Keybord %2 Mode %3',
		QH_IrPress:'Press',
		QH_IrPressOn:'Press on',
		QH_ir_send_nec:'Infrared emission %1 Port P2(L3) data %2 bits %3',
		QH_ir_send_raw:'Infrared emission Port P2(L3) %1 Array %2 Array length %3 frequency %4',
		QH_display:'Digit Port %1 decimal digits %2 number %3',
		QH_displayoff:'Turn off Digit Port %1'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
    	QH_BUTTON_LABEL:'---按钮---',
    	QH_SENSOR_LABEL:'---传感器---',
    	QH_BUZZER_LABEL:'---蜂鸣器---',
    	QH_SERVO_LABEL:'---舵机---',
    	QH_DCMOTO_LABEL:'---直流电机---',
    	QH_IR_LABEL:'---红外---',
    	QH_SERIAL_LABEL:'---串口---',
    	QH_SENSOR_CATEGORY:'传感器',
    	QH_ACTUATOR_CATEGORY:'执行器',
    	QH_COMMUNICATE_CATEGORY:'通讯',
    	QH_SMG_CATEGORY:'数码管',
    	QH_LEFT:'左',
    	QH_RIGHT:'右',
        QH_BUTTON_GENERAL:'按钮 端口 %1  左/右 %2',
        QH_BUTTON_BOTH:'左或右按钮 端口 %1',
        QH_BUTTONFUCTION_INIT:'启用多功能按钮 端口 %1',
        QH_BUTTONFUCTION_DO:'多功能按钮 端口 %1 左右 %2 触发方式 %3',
        QH_BUTTONSingleClick:"单击",
		QH_BUTTONDoubleClick:"双击",
		QH_BUTTONTripleClick:"三击",
		QH_BUTTONSingleLongClick:"长按",
		QH_BUTTONDoubleLongClick:"单击后长按",
		QH_BUTTONTripleLongClick:"双击后长按",
		QH_UltraSonicDistanceSensor:'超声波测距 端口 %1 单位 %2',
		QH_LINE_FOLLOWER:'巡线 端口 %1 左路 %2 右路 %3',
		QH_LIGHTSENSOR:'光线传感器 端口 %1',
		QH_SOUND:'声音传感器 端口 %1',
		QH_POTENTIOMETER:'电位传感器 端口 %1 左右 %2',
		QH_dht11:'温湿度传感器 端口 %1 参数 %2',
		QH_Temperature:'温度',
		QH_Humidity:'湿度',
		QH_ledlight:'LED 端口 %1 左/右 %2 状态 %3',
		QH_read_ledlight:'读取 LED 端口 %1 左/右 %2 ',
		QH_ledlight_PWM:'LED 端口 %1 左/右 %2 值(0~255) %3',
		QH_rgb_led:'RGB LED 端口 %1 总数 %2  灯号 %3 R %4 G %5 B %6',
		QH_rgb_led2:'RGB LED 端口 %1 总数 %2  灯号 %3 颜色 %4',
		QH_buzzer:'蜂鸣器 端口 %1 频率 %2 持续时间 %3',
		QH_buzzer_music:'蜂鸣器 端口 %1 演奏音乐 %2 ',
		QH_motor:'直流电机 端口 %1 速度(-255~255) %2',
		QH_servomotor360:'舵机360° 端口 %1 方向 %2 速度(0~10) %3',
		QH_CW:'正转',
		QH_CCW:'反转',
		QH_servomotor180:'舵机180° 端口 %1 速度 %2 角度(0~180) %3 是否可中断 %4',
		QH_Donotinterrupt:'不中断',
		QH_Interruptible:'中断',
		QH_servomotorread:'舵机读取角度 端口 %1',
		QH_ir_re2:'红外遥控 RC5 端口 %1 按键 %2 模式 %3',
		QH_IrPress:'按下',
		QH_IrPressOn:'按住',
		QH_ir_send_nec:'红外发射 模式 %1 端口 P2(L3) 数值 %2 比特数 %3',
		QH_ir_send_raw:'红外发射 端口 P2(L3) %1 数组 %2 数组长度 %3 频率 %4',
		QH_display:'数码管 端口 %1 小数位 %2 数字 %3',
		QH_displayoff:'关闭数码管 端口 %1'
    });
	Object.assign(Blockly.ScratchMsgs.locales["zh-tw"], {
        QH_BUTTON_LABEL:'---按鈕---',
        QH_SENSOR_LABEL:'---感測器---',
        QH_BUZZER_LABEL:'---蜂鳴器---',
        QH_SERVO_LABEL:'---舵機---',
        QH_DCMOTO_LABEL:'---直流電機---',
        QH_IR_LABEL:'---紅外---',
        QH_SERIAL_LABEL:'---串口---',
        QH_SENSOR_CATEGORY:'感測器',
        QH_ACTUATOR_CATEGORY:'執行器',
        QH_COMMUNICATE_CATEGORY:'通訊',
        QH_SMG_CATEGORY:'數碼管',
        QH_LEFT:'左',
        QH_RIGHT:'右',
        QH_BUTTON_GENERAL:'按鈕 端口 %1  左/右 %2',
        QH_BUTTON_BOTH:'左或右按鈕 端口 %1',
        QH_BUTTONFUCTION_INIT:'啟用多功能按鈕 端口 %1',
        QH_BUTTONFUCTION_DO:'多功能按鈕 端口 %1 左右 %2 觸發方式 %3',
        QH_BUTTONSingleClick:"單擊",
        QH_BUTTONDoubleClick:"雙擊",
        QH_BUTTONTripleClick:"三擊",
        QH_BUTTONSingleLongClick:"長按",
        QH_BUTTONDoubleLongClick:"單擊後長按",
        QH_BUTTONTripleLongClick:"雙擊後長按",
        QH_UltraSonicDistanceSensor:'超聲波測距 端口 %1 單位 %2',
        QH_LINE_FOLLOWER:'巡線 端口 %1 左路 %2 右路 %3',
        QH_LIGHTSENSOR:'光線感測器 端口 %1',
        QH_SOUND:'聲音感測器 端口 %1',
        QH_POTENTIOMETER:'電位感測器 端口 %1 左右 %2',
        QH_dht11:'溫濕度感測器 端口 %1 參數 %2',
        QH_Temperature:'溫度',
        QH_Humidity:'濕度',
        QH_ledlight:'LED 端口 %1 左/右 %2 狀態 %3',
        QH_read_ledlight:'讀取 LED 端口 %1 左/右 %2 ',
        QH_ledlight_PWM:'LED 端口 %1 左/右 %2 值(0~255) %3',
        QH_rgb_led:'RGB LED 端口 %1 總數 %2  燈號 %3 R %4 G %5 B %6',
        QH_rgb_led2:'RGB LED 端口 %1 總數 %2  燈號 %3 顏色 %4',
        QH_buzzer:'蜂鳴器 端口 %1 頻率 %2 持續時間 %3',
        QH_buzzer_music:'蜂鳴器 端口 %1 演奏音樂 %2 ',
        QH_motor:'直流電機 端口 %1 速度(-255~255) %2',
        QH_servomotor360:'舵機360° 端口 %1 方向 %2 速度(0~10) %3',
        QH_CW:'正轉',
        QH_CCW:'反轉',
        QH_servomotor180:'舵機180° 端口 %1 速度 %2 角度(0~180) %3 是否可中斷 %4',
        QH_Donotinterrupt:'不中斷',
        QH_Interruptible:'中斷',
        QH_servomotorread:'舵機讀取角度 端口 %1',
        QH_ir_re2:'紅外遙控 RC5 端口 %1 按鍵 %2 模式 %3',
        QH_IrPress:'按下',
        QH_IrPressOn:'按住',
        QH_ir_send_nec:'紅外發射 模式 %1 端口 P2(L3) 數值 %2 比特數 %3',
        QH_ir_send_raw:'紅外發射 端口 P2(L3) %1 數組 %2 數組長度 %3 頻率 %4',
        QH_display:'數碼管 端口 %1 小數位 %2 數字 %3',
        QH_displayoff:'關閉數碼管 端口 %1'
    });
    return Blockly;
}

exports = addMsg;
