/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        QH_LIST_CATEGORY:'List',
        lists_create_with:'Create list  name: %1 content:%2',
        lists_set_value:'List %1 which %2 set value %3',
        lists_create_with_item:'List %1的 which %2',
        lists_slice:'List %1 from %2 to %3',
        lists_built_in_function:'List %1  %2',
        lists_built_in_function_output:'List %1 . %2 value %3',
        lists_built_in_function_statement:'List %1 . %2 value %3',
        lists_append:'append',
        lists_count:'count',
        lists_extend:'extend',
        lists_index:'index',
        lists_pop:'pop',
        lists_remove:'remove',
        lists_clear:'clear',
        lists_reverse:'reverse',
        lists_copy:'copy',
        list_reverse:'reverse',
        lists_built_in_function_output2:'List %1 . %2 ',
        lists_built_in_function_statement2:'List %1 %2',
        list_tuple_to_list:'%1 %2',
        tolist:'Convertor to list',
        totuple:'Convertor to tuple',
        todict:'Convertor to dict',
        toset:'Convertor to set',
        tuple_len:'len',
        tuple_max:'max',
        tuple_min:'min',
        tuple_sum:'sum',
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        QH_LIST_CATEGORY:'列表',
        lists_create_with:'创建列表  名称: %1 内容:%2',
        lists_set_value:'列表 %1 第 %2 项赋值为:%3',
        lists_create_with_item:'列表 %1的第%2项',
        lists_slice:'列表 %1从%2到%3',
        lists_built_in_function:'列表 %1  %2',
        lists_built_in_function_output:'列表 %1 . %2 数值 %3',
        lists_built_in_function_statement:'列表 %1 . %2 数值 %3',
        lists_append:'尾部增加',
        lists_count:'计数',
        lists_extend:'扩展',
        lists_index:'索引',
        lists_pop:'弹出',
        lists_remove:'移除',
        lists_clear:'清空',
        lists_reverse:'反向',
        lists_copy:'拷贝',
        list_reverse:'逆序',
        lists_built_in_function_output2:'列表 %1 . %2 ',
        lists_built_in_function_statement2:'列表 %1 %2',
        list_tuple_to_list:'%1对象:%2',
        tolist:'转换为列表',
        totuple:'转换为元组',
        todict:'转换为字典',
        toset:'转换为集合',
        tuple_len:'长度',
        tuple_max:'最大',
        tuple_min:'最小',
        tuple_sum:'总和',
    });
    Object.assign(Blockly.ScratchMsgs.locales["zh-tw"], {
        QH_LIST_CATEGORY:'列表',
        lists_create_with:'創建列表  名稱: %1 內容:%2',
        lists_set_value:'列表 %1 第 %2 項賦值為:%3',
        lists_create_with_item:'列表 %1的第%2項',
        lists_slice:'列表 %1從%2到%3',
        lists_built_in_function:'列表 %1  %2',
        lists_built_in_function_output:'列表 %1 . %2 數值 %3',
        lists_built_in_function_statement:'列表 %1 . %2 數值 %3',
        lists_append:'尾部增加',
        lists_count:'計數',
        lists_extend:'擴展',
        lists_index:'索引',
        lists_pop:'彈出',
        lists_remove:'移除',
        lists_clear:'清空',
        lists_reverse:'反向',
        lists_copy:'拷貝',
        list_reverse:'逆序',
        lists_built_in_function_output2:'列表 %1 . %2 ',
        lists_built_in_function_statement2:'列表 %1 %2',
        list_tuple_to_list:'%1對象:%2',
        tolist:'轉換為列表',
        totuple:'轉換為元組',
        todict:'轉換為字典',
        toset:'轉換為集合',
        tuple_len:'長度',
        tuple_max:'最大',
        tuple_min:'最小',
        tuple_sum:'總和',
    });
    return Blockly;
}

exports = addMsg;
