name: Release

on:
  push:
    tags:
      - 'v*'
    paths-ignore:
      - 'README.md'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: resource-cli Install
        uses: actions/checkout@v2
        with:
          repository: aopu-edu/openblock-resource-cli
          ref: refs/heads/main
          token: ${{ secrets.GH_PAT }}
          path: openblock-resource-cli
      - run: |
          cd openblock-resource-cli
          npm install
          npm link

      - name: external-resources Install
        uses: actions/checkout@v2
        with:
          repository: aopu-edu/external-resources-qdp
          ref: refs/heads/qdp
          token: ${{ secrets.GH_PAT }}
          path: external-resources

      - name: Pro-process resources
        run: |
          cd external-resources
          opt-size
          gen-config --version=${{ github.ref_name }}

      - name: Get version
        id: get-version
        run: |
          version=`echo ${{ github.ref_name }} | sed -r 's/[v]+//g'`
          echo ::set-output name=VERSION::$version

      - name: Zip resources
        uses: vimtor/action-zip@v1
        with:
            files: ./external-resources
            dest: qdp-external-resources-${{ steps.get-version.outputs.VERSION }}.zip

      - name: Checksum
        run: sha256sum qdp-external-resources-*.zip >> ${{ steps.get-version.outputs.VERSION }}-checksums-sha256.txt

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: OpenBlock External Resources ${{ github.ref_name }}
          body: |
            ## Change Log (en)

            - **New feature**

                1. Update Traditional Chinese translation.

            ## 更改日志 (zh-cn)

            - **新功能**

                1. 更新繁体中文翻译。
          draft: true
          prerelease: false

      # Upload zip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: qdp-external-resources-${{ steps.get-version.outputs.VERSION }}.zip
          asset_name: qdp-external-resources-${{ steps.get-version.outputs.VERSION }}.zip
          asset_content_type: application/zip

      # Upload checksum
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.get-version.outputs.VERSION }}-checksums-sha256.txt
          asset_name: ${{ steps.get-version.outputs.VERSION }}-checksums-sha256.txt
          asset_content_type: text/plain

      # Upload to digitalocean
      - name: Release resources to digital ocean spaces
        run: |
          export DO_KEY_ID=${{ secrets.DO_KEY_ID }}
          export DO_SECRET_KEY=${{ secrets.DO_SECRET_KEY }}
          upload-file --filePath=qdp-external-resources-${{ steps.get-version.outputs.VERSION }}.zip
          upload-file --filePath=${{ steps.get-version.outputs.VERSION }}-checksums-sha256.txt
